import { Calculator } from "lucide-react";
import type { ReferenceCategory } from "./types";

const DOC = "https://typst.app/docs/reference/foundations/";

export const foundations: ReferenceCategory = {
  slug: "foundations",
  title: "Nền tảng (Foundations)",
  icon: Calculator,
  summary: "Kiểu dữ liệu cơ bản (số, chuỗi, mảng, từ điển, nội dung…), mô-đun calc/std/sys và các hàm tiện ích — đầy đủ phương thức theo Typst v0.14.2.",
  docUrl: DOC,
  fns: [
    {
      name: "calc", slug: "calc", kind: "module",
      signature: "calc.abs · pow · sqrt · root · min · max · round · floor · ceil · rem · gcd · pi · e ...",
      summary: "Mô-đun hàm toán học và xử lý giá trị số (41 hàm/hằng trong Typst v0.14.2).",
      docUrl: `${DOC}calc/`,
      snapshotId: "foundations-calc",
      params: [
        { name: "abs · pow(x,y) · sqrt · root(x,n) · exp · ln · log(x, base)", type: "→ số", desc: "Trị tuyệt đối, luỹ thừa, căn, mũ, logarit." },
        { name: "sin cos tan · asin acos atan atan2 · sinh cosh tanh", type: "→ số", desc: "Lượng giác & hyperbolic (đơn vị rad hoặc góc)." },
        { name: "round(x, digits) · floor · ceil · trunc · fract", type: "→ số", desc: "Làm tròn / lấy nguyên / phần lẻ." },
        { name: "min(..) · max(..) · clamp(x,lo,hi)", type: "→ số", desc: "Nhỏ nhất / lớn nhất / kẹp khoảng." },
        { name: "rem · quo · div-euclid · rem-euclid", type: "→ số", desc: "Phần dư / thương (thường và kiểu Euclid)." },
        { name: "gcd · lcm · fact · perm(n,k) · binom(n,k)", type: "→ số", desc: "ƯCLN/BCNN, giai thừa, chỉnh hợp, tổ hợp." },
        { name: "even · odd · norm(..)", type: "→ bool/số", desc: "Kiểm tra chẵn/lẻ; chuẩn (norm) của dãy giá trị." },
        { name: "pi · tau · e · inf", type: "hằng số", desc: "π, τ=2π, số e, vô cực." },
      ],
      examples: [`#calc.pow(2, 10)  // 1024
#calc.round(3.14159, digits: 2)  // 3.14`],
      members: [
        { name: "calc.pow", slug: "calc.pow", kind: "function", signature: "calc.pow(base, exponent)", summary: "Luỹ thừa base^exponent.", docUrl: `${DOC}calc/#definitions-pow`, params: [
          { name: "base", type: "int | float", positional: true, desc: "Cơ số." },
          { name: "exponent", type: "int | float", positional: true, desc: "Số mũ." },
        ] },
        { name: "calc.root", slug: "calc.root", kind: "function", signature: "calc.root(radicand, index)", summary: "Căn bậc index của radicand.", docUrl: `${DOC}calc/#definitions-root`, params: [
          { name: "radicand", type: "float", positional: true, desc: "Số dưới căn." },
          { name: "index", type: "int", positional: true, desc: "Bậc của căn." },
        ] },
        { name: "calc.round", slug: "calc.round", kind: "function", signature: "calc.round(value, digits)", summary: "Làm tròn tới số chữ số thập phân.", docUrl: `${DOC}calc/#definitions-round`, params: [
          { name: "value", type: "int | float", positional: true, desc: "Giá trị cần làm tròn." },
          { name: "digits", type: "int", default: "0", desc: "Số chữ số thập phân." },
        ] },
        { name: "calc.clamp", slug: "calc.clamp", kind: "function", signature: "calc.clamp(value, min, max)", summary: "Kẹp giá trị vào khoảng [min, max].", docUrl: `${DOC}calc/#definitions-clamp`, params: [
          { name: "value", type: "int | float", positional: true, desc: "Giá trị." },
          { name: "min", type: "int | float", positional: true, desc: "Cận dưới." },
          { name: "max", type: "int | float", positional: true, desc: "Cận trên." },
        ] },
        { name: "calc.min / calc.max", slug: "calc.min", kind: "function", signature: "calc.min(..values)  ·  calc.max(..values)", summary: "Nhỏ nhất / lớn nhất trong các giá trị.", docUrl: `${DOC}calc/#definitions-min`, params: [
          { name: "values", type: "any", positional: true, desc: "Các giá trị (biến thiên ..)." },
        ] },
        { name: "calc.rem / calc.quo", slug: "calc.rem", kind: "function", signature: "calc.rem(dividend, divisor)  ·  calc.quo(...)", summary: "Phần dư / thương nguyên của phép chia.", docUrl: `${DOC}calc/#definitions-rem`, params: [
          { name: "dividend", type: "int | float", positional: true, desc: "Số bị chia." },
          { name: "divisor", type: "int | float", positional: true, desc: "Số chia." },
        ] },
      ],
    },
    {
      name: "str", slug: "str", kind: "type",
      signature: 'str(value, base)  ·  "...".len() .upper() .split() ...',
      summary: "Chuỗi ký tự Unicode; nhiều phương thức xử lý văn bản.",
      docUrl: `${DOC}str/`,
      snapshotId: "foundations-str",
      params: [
        { name: ".len() · .at(i) · .first() · .last() · .rev()", type: "method", desc: "Độ dài / ký tự / đầu / cuối / đảo chuỗi." },
        { name: ".slice(a,b) · .clusters() · .codepoints() · .normalize(form)", type: "method", desc: "Cắt / tách cụm ký tự / điểm mã Unicode / chuẩn hoá." },
        { name: ".contains(p) · .starts-with(p) · .ends-with(p)", type: "method", desc: "Kiểm tra chứa / bắt đầu / kết thúc bằng mẫu." },
        { name: ".find(p) · .position(p) · .match(re) · .matches(re)", type: "method", desc: "Tìm chuỗi / vị trí / khớp regex (một / nhiều)." },
        { name: ".replace(p, w, count) · .trim(p, at) · .split(sep)", type: "method", desc: "Thay thế / cắt hai đầu / tách thành mảng." },
        { name: "str.to-unicode(c) · str.from-unicode(code)", type: "hàm", desc: "Chuyển ký tự ↔ mã điểm Unicode." },
      ],
      examples: [`#"a,b,c".split(",").len()  // 3`],
      members: [
        { name: "str.slice", slug: "str.slice", kind: "function", signature: "s.slice(start, end, count)", summary: "Cắt một đoạn con của chuỗi.", docUrl: `${DOC}str/#definitions-slice`, params: [
          { name: "start", type: "int", positional: true, desc: "Vị trí byte bắt đầu." },
          { name: "end", type: "none | int", default: "none", positional: true, desc: "Vị trí kết thúc." },
        ] },
        { name: "str.split", slug: "str.split", kind: "function", signature: "s.split(pattern)", summary: "Tách chuỗi theo mẫu, trả về mảng.", docUrl: `${DOC}str/#definitions-split`, params: [
          { name: "pattern", type: "none | str | regex", default: "none", positional: true, desc: "Dấu/mẫu phân tách (none = theo khoảng trắng)." },
        ] },
        { name: "str.replace", slug: "str.replace", kind: "function", signature: "s.replace(pattern, with, count)", summary: "Thay thế các lần khớp.", docUrl: `${DOC}str/#definitions-replace`, params: [
          { name: "pattern", type: "str | regex", positional: true, desc: "Mẫu cần thay." },
          { name: "with", type: "str | function", positional: true, desc: "Chuỗi/hàm thay thế." },
          { name: "count", type: "int", default: "auto", desc: "Số lần thay tối đa." },
        ] },
        { name: "str.contains / find / position", slug: "str.contains", kind: "function", signature: "s.contains(p)  ·  s.find(p)  ·  s.position(p)", summary: "Kiểm tra chứa / tìm chuỗi khớp / vị trí khớp.", docUrl: `${DOC}str/#definitions-contains`, params: [
          { name: "pattern", type: "str | regex", positional: true, desc: "Mẫu cần tìm." },
        ] },
        { name: "str.trim", slug: "str.trim", kind: "function", signature: "s.trim(pattern, at, repeat)", summary: "Cắt bỏ khoảng trắng/mẫu ở hai đầu.", docUrl: `${DOC}str/#definitions-trim`, params: [
          { name: "pattern", type: "none | str | regex", default: "none", positional: true, desc: "Mẫu cần cắt (none = khoảng trắng)." },
          { name: "at", type: "alignment", default: "auto", desc: "Chỉ cắt đầu (start) hoặc cuối (end)." },
        ] },
      ],
    },
    {
      name: "array", slug: "array", kind: "type",
      signature: "(1, 2, 3)  ·  .map() .filter() .fold() .sorted() ...",
      summary: "Dãy các giá trị có thứ tự; nhiều phương thức biến đổi.",
      docUrl: `${DOC}array/`,
      snapshotId: "foundations-array",
      params: [
        { name: ".len() · .at(i, default) · .first() · .last()", type: "method", desc: "Độ dài / truy cập phần tử (âm = từ cuối)." },
        { name: ".push(v) · .pop() · .insert(i,v) · .remove(i)", type: "method", desc: "Thêm/bớt phần tử." },
        { name: ".slice(a,b) · .rev() · .flatten() · .chunks(n) · .windows(n)", type: "method", desc: "Cắt / đảo / làm phẳng / chia khối / cửa sổ trượt." },
        { name: ".contains(v) · .find(f) · .position(f) · .any(f) · .all(f)", type: "method", desc: "Kiểm tra chứa / tìm / điều kiện tồn tại / mọi." },
        { name: ".map(f) · .filter(f) · .enumerate() · .zip(..) · .fold(init,f) · .reduce(f)", type: "method", desc: "Biến đổi / lọc / đánh số / ghép cặp / gộp." },
        { name: ".sum() · .product() · .sorted(key,by) · .dedup() · .rev()", type: "method", desc: "Tổng / tích / sắp xếp / khử trùng lặp." },
        { name: ".join(sep, last) · .intersperse(v) · .split(at) · .to-dict() · array.range(..)", type: "method", desc: "Nối / chèn xen / tách / đổi sang dict / dãy số." },
      ],
      examples: [`#(3, 1, 2).sorted()  // (1, 2, 3)`],
      members: [
        { name: "array.map", slug: "array.map", kind: "function", signature: "a.map(mapper)", summary: "Biến đổi từng phần tử bằng một hàm.", docUrl: `${DOC}array/#definitions-map`, params: [
          { name: "mapper", type: "function", positional: true, desc: "Hàm nhận phần tử, trả về giá trị mới." },
        ] },
        { name: "array.filter", slug: "array.filter", kind: "function", signature: "a.filter(test)", summary: "Giữ lại phần tử thoả điều kiện.", docUrl: `${DOC}array/#definitions-filter`, params: [
          { name: "test", type: "function", positional: true, desc: "Hàm trả về true/false." },
        ] },
        { name: "array.fold", slug: "array.fold", kind: "function", signature: "a.fold(init, folder)", summary: "Gộp mảng về một giá trị (reduce).", docUrl: `${DOC}array/#definitions-fold`, params: [
          { name: "init", type: "any", positional: true, desc: "Giá trị khởi tạo." },
          { name: "folder", type: "function", positional: true, desc: "Hàm (accumulator, item) → accumulator." },
        ] },
        { name: "array.sorted", slug: "array.sorted", kind: "function", signature: "a.sorted(key, by)", summary: "Trả về mảng đã sắp xếp.", docUrl: `${DOC}array/#definitions-sorted`, params: [
          { name: "key", type: "function", default: "none", desc: "Hàm trích khoá so sánh." },
          { name: "by", type: "function", default: "auto", desc: "Hàm so sánh tuỳ chỉnh." },
        ] },
        { name: "array.at / push / pop", slug: "array.at", kind: "function", signature: "a.at(index, default)  ·  a.push(value)  ·  a.pop()", summary: "Truy cập / thêm / bớt phần tử.", docUrl: `${DOC}array/#definitions-at`, params: [
          { name: "index", type: "int", positional: true, desc: "Vị trí (âm = tính từ cuối)." },
          { name: "default", type: "any", default: "—", desc: "Giá trị mặc định khi vượt biên (cho .at)." },
        ] },
        { name: "array.join", slug: "array.join", kind: "function", signature: "a.join(separator, last)", summary: "Nối các phần tử thành một giá trị.", docUrl: `${DOC}array/#definitions-join`, params: [
          { name: "separator", type: "any", default: "none", positional: true, desc: "Dấu ngăn giữa phần tử." },
          { name: "last", type: "any", default: "none", desc: "Dấu ngăn trước phần tử cuối." },
        ] },
      ],
    },
    {
      name: "dictionary", slug: "dictionary", kind: "type",
      signature: "(khoa: giá-trị)  ·  .keys() .values() .pairs() ...",
      summary: "Ánh xạ từ khóa chuỗi sang giá trị.",
      docUrl: `${DOC}dictionary/`,
      snapshotId: "foundations-dictionary",
      params: [
        { name: ".keys() · .values() · .pairs()", type: "method", desc: "Danh sách khóa / giá trị / cặp." },
        { name: ".at(k) · .insert(k,v) · .remove(k)", type: "method", desc: "Truy cập / thêm / xoá theo khóa." },
        { name: ".len()", type: "method", desc: "Số cặp khóa-giá trị." },
      ],
      examples: [`#(ten: "An", tuoi: 20).at("ten")  // "An"`],
      members: [
        { name: "dictionary.at", slug: "dictionary.at", kind: "function", signature: "d.at(key, default)", summary: "Lấy giá trị theo khoá (có giá trị mặc định).", docUrl: `${DOC}dictionary/#definitions-at`, params: [
          { name: "key", type: "str", positional: true, desc: "Khoá cần lấy." },
          { name: "default", type: "any", default: "—", desc: "Giá trị trả về nếu thiếu khoá." },
        ] },
        { name: "dictionary.insert / remove", slug: "dictionary.insert", kind: "function", signature: "d.insert(key, value)  ·  d.remove(key, default)", summary: "Thêm/cập nhật hoặc xoá một cặp khoá-giá trị.", docUrl: `${DOC}dictionary/#definitions-insert`, params: [
          { name: "key", type: "str", positional: true, desc: "Khoá." },
          { name: "value", type: "any", positional: true, desc: "Giá trị (cho .insert)." },
        ] },
        { name: "dictionary.keys / values / pairs", slug: "dictionary.keys", kind: "function", signature: "d.keys()  ·  d.values()  ·  d.pairs()", summary: "Danh sách khoá / giá trị / cặp (khoá, giá trị).", docUrl: `${DOC}dictionary/#definitions-keys`, params: [] },
      ],
    },
    {
      name: "int", slug: "int", kind: "type",
      signature: "int(value, base)  ·  10  0xff  1_000",
      summary: "Số nguyên (dương, âm, không).",
      docUrl: `${DOC}int/`,
      snapshotId: "foundations-int",
      params: [
        { name: "int(value, base)", type: "constructor", desc: "Chuyển chuỗi/float/bool sang số nguyên." },
        { name: ".signum()", type: "method", desc: "Dấu: -1 / 0 / 1." },
        { name: ".bit-not() · .bit-and(n) · .bit-or(n) · .bit-xor(n) · .bit-lshift(n) · .bit-rshift(n)", type: "method", desc: "Phép trên bit." },
        { name: "int.from-bytes(bytes) · .to-bytes()", type: "hàm/method", desc: "Chuyển số nguyên ↔ chuỗi byte." },
      ],
      examples: [`#int("42") + 0xff`],
    },
    {
      name: "float", slug: "float", kind: "type",
      signature: "float(value)  ·  3.14  1e5  1.5e-3",
      summary: "Số dấu phẩy động.",
      docUrl: `${DOC}float/`,
      snapshotId: "foundations-float",
      params: [
        { name: "float(value)", type: "constructor", desc: "Chuyển sang số thực." },
        { name: ".is-nan() · .is-infinite() · .signum()", type: "method", desc: "Kiểm tra NaN / vô cực; dấu của số." },
        { name: "float.from-bytes(bytes) · .to-bytes()", type: "hàm/method", desc: "Chuyển số thực ↔ chuỗi byte." },
      ],
      examples: [`#float("3.14") * 2`],
    },
    {
      name: "decimal", slug: "decimal", kind: "type",
      signature: "decimal(value)",
      summary: "Số thập phân dấu phẩy cố định — chính xác cho tính tiền tệ.",
      docUrl: `${DOC}decimal/`,
      snapshotId: "foundations-decimal",
      params: [{ name: "decimal(value)", type: "constructor", desc: "Tạo số thập phân chính xác từ chuỗi/số nguyên." }],
      examples: [`#(decimal("0.1") + decimal("0.2"))  // 0.3`],
    },
    {
      name: "datetime", slug: "datetime", kind: "type",
      signature: "datetime(year, month, day, ...)  ·  datetime.today()",
      summary: "Ngày, giờ hoặc cả hai; định dạng bằng .display().",
      docUrl: `${DOC}datetime/`,
      snapshotId: "foundations-datetime",
      params: [
        { name: "datetime(year, month, day, hour, minute, second)", type: "constructor", desc: "Tạo ngày/giờ từ các thành phần." },
        { name: "datetime.today(offset)", type: "hàm", desc: "Ngày hôm nay (cần context)." },
        { name: ".display(format)", type: "method", desc: 'Định dạng, vd "[day]/[month]/[year]".' },
        { name: ".year() · .month() · .day()", type: "method", desc: "Năm / tháng / ngày." },
        { name: ".hour() · .minute() · .second()", type: "method", desc: "Giờ / phút / giây." },
        { name: ".ordinal() · .weekday()", type: "method", desc: "Ngày thứ mấy trong năm / thứ trong tuần." },
      ],
      examples: [`#datetime.today().display("[day]/[month]/[year]")`],
    },
    {
      name: "duration", slug: "duration", kind: "type",
      signature: "duration(days, hours, minutes, seconds, weeks)",
      summary: "Khoảng thời gian; cộng/trừ được với datetime.",
      docUrl: `${DOC}duration/`,
      snapshotId: "foundations-duration",
      params: [
        { name: "duration(weeks, days, hours, minutes, seconds)", type: "constructor", desc: "Tạo khoảng thời gian." },
        { name: ".weeks() · .days() · .hours() · .minutes() · .seconds()", type: "method", desc: "Quy đổi tổng khoảng thời gian sang đơn vị tương ứng." },
      ],
      examples: [`#duration(days: 3).hours()  // 72`],
    },
    {
      name: "content", slug: "content", kind: "type",
      signature: "[ *nội dung* ]  ·  .func() .fields() .at() ...",
      summary: "Một mẩu nội dung tài liệu có thể dựng (render).",
      docUrl: `${DOC}content/`,
      snapshotId: "foundations-content",
      params: [
        { name: ".func()", type: "method", desc: "Hàm phần tử tạo ra nội dung này." },
        { name: ".fields() · .at(field)", type: "method", desc: "Truy cập các trường của phần tử." },
        { name: ".has(field) · .location()", type: "method", desc: "Kiểm tra trường / vị trí." },
      ],
      examples: [`#let x = [*Đậm*]
#x.func()  // strong`],
    },
    {
      name: "arguments", slug: "arguments", kind: "type",
      signature: "arguments  ·  ..args  ·  .pos() .named() .at()",
      summary: "Tập đối số đã thu giữ truyền vào một hàm (dùng với toán tử ..).",
      docUrl: `${DOC}arguments/`,
      snapshotId: "foundations-arguments",
      params: [
        { name: ".pos()", type: "method", desc: "Mảng đối số vị trí." },
        { name: ".named()", type: "method", desc: "Từ điển đối số có tên." },
        { name: ".at(key, default)", type: "method", desc: "Lấy đối số theo vị trí (int) hoặc tên (str)." },
      ],
      examples: [`#let f(..args) = args.pos().len()
#f(1, 2, 3)  // 3`],
    },
    {
      name: "function", slug: "function", kind: "type",
      signature: "(x) => x + 1  ·  .with() .where()",
      summary: "Ánh xạ từ đối số sang giá trị trả về (kể cả hàm phần tử).",
      docUrl: `${DOC}function/`,
      snapshotId: "foundations-function",
      params: [
        { name: ".with(..args)", type: "method", desc: "Cố định sẵn một số đối số (partial)." },
        { name: ".where(..fields)", type: "method", desc: "Bộ chọn theo trường (cho show/set)." },
      ],
      examples: [`#let add2 = (x) => x + 2
#add2(5)  // 7`],
    },
    {
      name: "regex", slug: "regex", kind: "type",
      signature: 'regex("pattern")',
      summary: "Biểu thức chính quy; dùng với .find/.match/.replace và show rule.",
      docUrl: `${DOC}regex/`,
      snapshotId: "foundations-regex",
      params: [{ name: 'regex("...")', type: "constructor", desc: "Tạo mẫu regex." }],
      examples: [`#"abc123".find(regex("\\d+"))  // "123"`],
    },
    {
      name: "symbol", slug: "symbol", kind: "type",
      signature: "symbol(..variants)  ·  Symbol",
      summary: "Ký hiệu Unicode với nhiều biến thể chọn qua cú pháp chấm (vd arrow.r).",
      docUrl: `${DOC}symbol/`,
      snapshotId: "foundations-symbol",
      params: [{ name: "symbol(string | (modifiers, string))", type: "constructor", desc: "Định nghĩa ký hiệu tùy biến có biến thể." }],
      examples: [`#sym.arrow.r  // →`],
    },
    {
      name: "label", slug: "label", kind: "type",
      signature: "<nhan>  ·  label(\"ten\")",
      summary: "Nhãn đánh dấu/tham chiếu một phần tử.",
      docUrl: `${DOC}label/`,
      snapshotId: "foundations-label",
      params: [{ name: 'label("name")', type: "constructor", desc: "Tạo nhãn từ chuỗi." }],
      examples: [`= Mở đầu <intro>
Xem @intro.`],
    },
    {
      name: "selector", slug: "selector", kind: "type",
      signature: "heading.where(level: 1)  ·  a.or(b)  ·  regex(...)",
      summary: "Bộ lọc chọn phần tử (dùng cho show rule, query, locate).",
      docUrl: `${DOC}selector/`,
      snapshotId: "foundations-selector",
      params: [
        { name: ".or() .and() .before() .after()", type: "method", desc: "Kết hợp/giới hạn phạm vi chọn." },
      ],
      examples: [`#show heading.where(level: 1): set text(navy)`],
    },
    {
      name: "bytes", slug: "bytes", kind: "type",
      signature: "bytes(value)  ·  .len() .slice() .at()",
      summary: "Dãy byte (dữ liệu nhị phân).",
      docUrl: `${DOC}bytes/`,
      snapshotId: "foundations-bytes",
      params: [
        { name: "bytes(array | str)", type: "constructor", desc: "Tạo dữ liệu nhị phân từ mảng số hoặc chuỗi." },
        { name: ".len() · .at(i) · .slice(a, b)", type: "method", desc: "Độ dài / byte tại vị trí / cắt đoạn." },
      ],
      examples: [`#bytes((104, 105)).len()  // 2`],
    },
    {
      name: "version", slug: "version", kind: "type",
      signature: "version(0, 14, 2)  ·  .at(i)",
      summary: "Phiên bản gồm nhiều thành phần số.",
      docUrl: `${DOC}version/`,
      snapshotId: "foundations-version",
      params: [{ name: "version(..components)", type: "constructor", desc: "Tạo phiên bản nhiều cấp." }],
      examples: [`#version(0, 14, 2).at(1)  // 14`],
    },
    {
      name: "module", slug: "module", kind: "type",
      signature: "module  ·  #import / #include",
      summary: "Tập hợp biến và hàm liên quan (file hoặc package).",
      docUrl: `${DOC}module/`,
      params: [{ name: "#import \"...\" · #import emoji", type: "cú pháp", desc: "Nạp module và truy cập thành viên." }],
      examples: [`#import "phu-luc.typ": ten-ham`],
    },
    {
      name: "none", slug: "none", kind: "type",
      signature: "none",
      summary: "Giá trị biểu thị sự vắng mặt; nhiều tham số nhận none để 'tắt'.",
      docUrl: `${DOC}none/`,
      params: [],
      examples: [`#set page(numbering: none)`],
    },
    {
      name: "auto", slug: "auto", kind: "type",
      signature: "auto",
      summary: "Giá trị mặc định thông minh do hệ thống tự chọn.",
      docUrl: `${DOC}auto/`,
      params: [],
      examples: [`#set page(margin: auto)`],
    },
    {
      name: "bool", slug: "bool", kind: "type",
      signature: "true · false",
      summary: "Kiểu logic hai trạng thái.",
      docUrl: `${DOC}bool/`,
      params: [],
      examples: [`#set par(justify: true)`],
    },
    {
      name: "type", slug: "type", kind: "function",
      signature: "type(value)",
      summary: "Trả về kiểu của một giá trị.",
      docUrl: `${DOC}type/`,
      snapshotId: "foundations-type",
      params: [{ name: "value", type: "any", positional: true, desc: "Giá trị cần xác định kiểu." }],
      examples: [`#type(10)  // integer`],
    },
    {
      name: "repr", slug: "repr", kind: "function",
      signature: "repr(value)",
      summary: "Chuỗi biểu diễn (debug) của một giá trị.",
      docUrl: `${DOC}repr/`,
      snapshotId: "foundations-repr",
      params: [{ name: "value", type: "any", positional: true, desc: "Giá trị cần biểu diễn." }],
      examples: [`#repr((1, 2))  // "(1, 2)"`],
    },
    {
      name: "assert", slug: "assert", kind: "function",
      signature: "assert(condition, message)  ·  assert.eq · assert.ne",
      summary: "Đảm bảo một điều kiện đúng, nếu không thì báo lỗi.",
      docUrl: `${DOC}assert/`,
      params: [
        { name: "condition", type: "bool", positional: true, desc: "Điều kiện cần thỏa." },
        { name: "message", type: "str", settable: true, desc: "Thông báo lỗi khi sai." },
      ],
      examples: [`#assert(1 < 2, message: "sai logic")`],
    },
    {
      name: "eval", slug: "eval", kind: "function",
      signature: "eval(source, mode, scope)",
      summary: "Đánh giá (thực thi) một chuỗi như mã Typst.",
      docUrl: `${DOC}eval/`,
      snapshotId: "foundations-eval",
      params: [
        { name: "source", type: "str", positional: true, desc: "Mã nguồn cần đánh giá." },
        { name: "mode", type: "str", default: '"code"', settable: true, desc: '"code" | "markup" | "math".' },
        { name: "scope", type: "dictionary", default: "(:)", settable: true, desc: "Biến bổ sung cho ngữ cảnh." },
      ],
      examples: [`#eval("1 + 2")  // 3`],
    },
    {
      name: "panic", slug: "panic", kind: "function",
      signature: "panic(..values)",
      summary: "Dừng biên dịch và báo lỗi ngay (gỡ rối).",
      docUrl: `${DOC}panic/`,
      params: [{ name: "values", type: "any", positional: true, desc: "Thông tin kèm theo lỗi." }],
      examples: [`#panic("không thể xảy ra")`],
    },
    {
      name: "plugin", slug: "plugin", kind: "function",
      signature: 'plugin("module.wasm")',
      summary: "Nạp một module WebAssembly để mở rộng chức năng.",
      docUrl: `${DOC}plugin/`,
      params: [{ name: "path", type: "str | bytes", positional: true, desc: "Đường dẫn file .wasm." }],
      examples: [`#let p = plugin("hash.wasm")`],
    },
    {
      name: "std", slug: "std", kind: "module",
      signature: "std.heading · std.table ...",
      summary: "Mô-đun chứa toàn bộ mục truy cập toàn cục (thư viện chuẩn) — hữu ích khi tên bị che.",
      docUrl: `${DOC}std/`,
      params: [],
      examples: [`#std.text(fill: red)[…]`],
    },
    {
      name: "sys", slug: "sys", kind: "module",
      signature: "sys.version · sys.inputs",
      summary: "Tương tác với môi trường biên dịch (phiên bản, tham số --input).",
      docUrl: `${DOC}sys/`,
      params: [
        { name: "sys.version", type: "version", desc: "Phiên bản Typst đang chạy." },
        { name: "sys.inputs", type: "dictionary", desc: "Tham số truyền qua dòng lệnh." },
      ],
      examples: [`#context sys.version`],
    },
  ],
};

// Hiển thị theo thứ tự chữ cái (giống sidebar typst.app/docs).
foundations.fns.sort((a, b) => a.name.localeCompare(b.name));
