import { LayoutPanelTop } from "lucide-react";
import type { ReferenceCategory } from "./types";

const DOC = "https://typst.app/docs/reference/layout/";
const TRACK = "auto | int | relative | fraction | array";
const CELL_STROKE = "none | length | color | gradient | stroke | array | dictionary | function";
const FILL = "none | color | gradient | tiling";
const SHAPE_STROKE = "none | length | color | gradient | stroke | dictionary";

export const layout: ReferenceCategory = {
  slug: "layout",
  title: "Bố cục (Layout)",
  icon: LayoutPanelTop,
  summary: "Khổ trang, lề, căn lề, lưới, cột, xếp chồng, đặt vị trí, khoảng trắng, biến hình và các kiểu đo lường.",
  docUrl: DOC,
  fns: [
    {
      name: "page",
      slug: "page",
      kind: "element",
      signature: "page(paper, width, height, flipped, margin, binding, columns, fill, numbering, number-align, header, footer, background, foreground, body)",
      summary: "Bố cục nội dung lên trang: khổ giấy, lề, số trang, đầu/chân trang, nền.",
      docUrl: `${DOC}page/`,
      params: [
        { name: "paper", type: "str", default: '"a4"', settable: true, desc: 'Khổ giấy chuẩn ("a4", "us-letter"...).' },
        { name: "width", type: "auto | length", default: "595.28pt", settable: true, desc: "Chiều rộng trang." },
        { name: "height", type: "auto | length", default: "841.89pt", settable: true, desc: "Chiều cao trang." },
        { name: "flipped", type: "bool", default: "false", settable: true, desc: "Xoay ngang (landscape)." },
        { name: "margin", type: "auto | relative | dictionary", default: "auto", settable: true, desc: "Lề trang (auto ≈ 2.5cm cho A4); dict để đặt riêng từng cạnh." },
        { name: "binding", type: "auto | alignment", default: "auto", settable: true, desc: "Cạnh đóng gáy (trái/phải)." },
        { name: "columns", type: "int", default: "1", settable: true, desc: "Số cột trên trang." },
        { name: "fill", type: "none | auto | color | gradient | tiling", default: "auto", settable: true, desc: "Màu nền trang." },
        { name: "numbering", type: "none | str | function", default: "none", settable: true, desc: 'Kiểu đánh số trang, vd "1", "1/1".' },
        { name: "number-align", type: "alignment", default: "center + bottom", settable: true, desc: "Vị trí số trang." },
        { name: "header", type: "none | auto | content", default: "auto", settable: true, desc: "Nội dung đầu trang." },
        { name: "footer", type: "none | auto | content", default: "auto", settable: true, desc: "Nội dung chân trang." },
        { name: "background", type: "none | content", default: "none", settable: true, desc: "Lớp nền phía sau nội dung." },
        { name: "foreground", type: "none | content", default: "none", settable: true, desc: "Lớp phủ phía trước nội dung (vd watermark)." },
        { name: "body", type: "content", positional: true, desc: "Nội dung trang." },
      ],
      examples: [`#set page(paper: "a4", margin: 2.5cm, numbering: "1")`],
    },
    {
      name: "par",
      slug: "par-layout",
      kind: "element",
      signature: "par(...)  → xem Model/par",
      summary: "Đoạn văn (giãn dòng, căn đều, thụt đầu dòng) — chi tiết ở nhóm Model.",
      docUrl: "https://typst.app/docs/reference/model/par/",
      params: [
        { name: "leading", type: "length", default: "0.65em", settable: true, desc: "Khoảng cách dòng." },
        { name: "justify", type: "bool", default: "false", settable: true, desc: "Căn đều hai bên." },
        { name: "first-line-indent", type: "length | dictionary", default: "0pt", settable: true, desc: "Thụt dòng đầu đoạn." },
      ],
      examples: [`#set par(justify: true, leading: 1em)`],
    },
    {
      name: "align",
      slug: "align",
      kind: "function",
      signature: "align(alignment, body)",
      summary: "Căn nội dung theo chiều ngang và/hoặc dọc.",
      docUrl: `${DOC}align/`,
      snapshotId: "layout-align",
      params: [
        { name: "alignment", type: "alignment", default: "start + top", positional: true, desc: "Vị trí căn: left/center/right + top/horizon/bottom." },
        { name: "body", type: "content", positional: true, desc: "Nội dung cần căn." },
      ],
      examples: [`#align(center)[Văn bản căn giữa]`],
      paramExamples: [
        { caption: "alignment — căn trái/giữa/phải", snapshotId: "layout-align-variants", width: "300pt", code: `#align(left)[Căn trái]
#align(center)[Căn giữa]
#align(right)[Căn phải]` },
      ],
    },
    {
      name: "grid",
      slug: "grid",
      kind: "function",
      signature: "grid(columns, rows, gutter, column-gutter, row-gutter, inset, align, fill, stroke, ..children)",
      summary: "Sắp xếp nội dung thành lưới hàng/cột. Kèm grid.cell, grid.header, grid.footer, grid.hline, grid.vline.",
      docUrl: `${DOC}grid/`,
      snapshotId: "layout-grid",
      params: [
        { name: "columns", type: TRACK, default: "()", settable: true, desc: "Số/kích thước cột; dùng fr để chia tỉ lệ." },
        { name: "rows", type: TRACK, default: "()", settable: true, desc: "Số/kích thước hàng." },
        { name: "gutter", type: TRACK, default: "()", settable: true, desc: "Khoảng hở chung giữa các ô." },
        { name: "column-gutter", type: TRACK, default: "()", settable: true, desc: "Khoảng hở giữa cột." },
        { name: "row-gutter", type: TRACK, default: "()", settable: true, desc: "Khoảng hở giữa hàng." },
        { name: "inset", type: "relative | array | dictionary | function", default: "0pt", settable: true, desc: "Đệm trong ô (grid mặc định 0)." },
        { name: "align", type: "auto | array | alignment | function", default: "auto", settable: true, desc: "Căn lề nội dung ô." },
        { name: "fill", type: "none | color | gradient | tiling | array | function", default: "none", settable: true, desc: "Màu nền ô." },
        { name: "stroke", type: CELL_STROKE, default: "none", settable: true, desc: "Nét kẻ ô (grid mặc định không kẻ)." },
        { name: "children", type: "content", positional: true, desc: "Nội dung các ô (biến thiên ..)." },
      ],
      examples: [`#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [Trái], [Phải],
)`],
      paramExamples: [
        { caption: "columns + fill + stroke — lưới 2 cột có nền/viền", snapshotId: "layout-grid-fill", width: "300pt", code: `#grid(
  columns: (1fr, 1fr),
  inset: 6pt,
  stroke: 0.5pt,
  fill: (_, y) => if y == 0 { luma(230) },
  [Cột A], [Cột B],
  [Dữ liệu 1], [Dữ liệu 2],
)` },
      ],
      members: [
        {
          name: "grid.cell", slug: "grid.cell", kind: "function",
          signature: "grid.cell(x, y, colspan, rowspan, fill, align, inset, stroke, breakable, body)",
          summary: "Ô lưới tuỳ biến: gộp ô, đổi màu/căn lề/nét riêng.",
          docUrl: `${DOC}grid/#definitions-cell`,
          params: [
            { name: "x", type: "auto | int", default: "auto", desc: "Chỉ số cột (0-based)." },
            { name: "y", type: "auto | int", default: "auto", desc: "Chỉ số hàng (0-based)." },
            { name: "colspan", type: "int", default: "1", desc: "Số cột ô chiếm." },
            { name: "rowspan", type: "int", default: "1", desc: "Số hàng ô chiếm." },
            { name: "fill", type: "auto | none | color | gradient | tiling", default: "auto", desc: "Màu nền ô." },
            { name: "align", type: "auto | alignment", default: "auto", desc: "Căn lề nội dung ô." },
            { name: "inset", type: "auto | relative | dictionary", default: "auto", desc: "Đệm trong ô." },
            { name: "stroke", type: CELL_STROKE, default: "auto", desc: "Nét kẻ riêng cho ô." },
            { name: "breakable", type: "auto | bool", default: "auto", desc: "Cho ô ngắt qua trang." },
            { name: "body", type: "content", positional: true, desc: "Nội dung ô." },
          ],
          paramExamples: [
            { caption: "colspan — ô gộp nhiều cột", snapshotId: "layout-gridcell-colspan", width: "300pt", code: `#grid(
  columns: 3,
  inset: 6pt,
  stroke: 0.5pt,
  grid.cell(colspan: 3, fill: luma(230))[Tiêu đề trải 3 cột],
  [a], [b], [c],
)` },
          ],
        },
        {
          name: "grid.header", slug: "grid.header", kind: "function",
          signature: "grid.header(repeat, level, ..children)",
          summary: "Nhóm hàng tiêu đề của lưới; lặp lại ở mỗi trang.",
          docUrl: `${DOC}grid/#definitions-header`,
          params: [
            { name: "repeat", type: "bool", default: "true", desc: "Lặp lại khi sang trang." },
            { name: "level", type: "int", default: "1", desc: "Cấp tiêu đề." },
            { name: "children", type: "content", positional: true, desc: "Các ô tiêu đề." },
          ],
        },
        {
          name: "grid.footer", slug: "grid.footer", kind: "function",
          signature: "grid.footer(repeat, ..children)",
          summary: "Nhóm hàng chân của lưới; lặp lại ở mỗi trang.",
          docUrl: `${DOC}grid/#definitions-footer`,
          params: [
            { name: "repeat", type: "bool", default: "true", desc: "Lặp lại khi sang trang." },
            { name: "children", type: "content", positional: true, desc: "Các ô chân." },
          ],
        },
        {
          name: "grid.hline", slug: "grid.hline", kind: "function",
          signature: "grid.hline(y, start, end, stroke, position)",
          summary: "Đường kẻ ngang tuỳ biến trong lưới.",
          docUrl: `${DOC}grid/#definitions-hline`,
          params: [
            { name: "y", type: "auto | int", default: "auto", desc: "Vị trí hàng." },
            { name: "start", type: "int", default: "0", desc: "Cột bắt đầu." },
            { name: "end", type: "none | int", default: "none", desc: "Cột kết thúc." },
            { name: "stroke", type: CELL_STROKE, default: "1pt + black", desc: "Kiểu nét." },
            { name: "position", type: "alignment", default: "top", desc: "Trên/dưới hàng." },
          ],
        },
        {
          name: "grid.vline", slug: "grid.vline", kind: "function",
          signature: "grid.vline(x, start, end, stroke, position)",
          summary: "Đường kẻ dọc tuỳ biến trong lưới.",
          docUrl: `${DOC}grid/#definitions-vline`,
          params: [
            { name: "x", type: "auto | int", default: "auto", desc: "Vị trí cột." },
            { name: "start", type: "int", default: "0", desc: "Hàng bắt đầu." },
            { name: "end", type: "none | int", default: "none", desc: "Hàng kết thúc." },
            { name: "stroke", type: CELL_STROKE, default: "1pt + black", desc: "Kiểu nét." },
            { name: "position", type: "alignment", default: "start", desc: "Trái/phải cột." },
          ],
        },
      ],
    },
    {
      name: "columns",
      slug: "columns",
      kind: "function",
      signature: "columns(count, gutter, body)",
      summary: "Chia một vùng thành nhiều cột bằng nhau (văn bản chảy qua các cột).",
      docUrl: `${DOC}columns/`,
      snapshotId: "layout-columns",
      params: [
        { name: "count", type: "int", default: "2", positional: true, desc: "Số cột." },
        { name: "gutter", type: "relative", default: "4% + 0pt", settable: true, desc: "Khoảng hở giữa các cột." },
        { name: "body", type: "content", positional: true, desc: "Nội dung chia cột." },
      ],
      examples: [`#columns(2)[Văn bản dài chảy qua hai cột...]`],
      paramExamples: [
        { caption: "count + gutter — chia 2 cột", snapshotId: "layout-columns-count", width: "360pt", code: `#columns(2, gutter: 1.5em)[#lorem(40)]` },
      ],
    },
    {
      name: "stack",
      slug: "stack",
      kind: "function",
      signature: "stack(dir, spacing, ..children)",
      summary: "Xếp nội dung và khoảng cách theo một hướng (ngang/dọc).",
      docUrl: `${DOC}stack/`,
      snapshotId: "layout-stack",
      params: [
        { name: "dir", type: "direction", default: "ttb", settable: true, desc: "Hướng xếp: ltr/rtl/ttb/btt." },
        { name: "spacing", type: "none | relative | fraction", default: "none", settable: true, desc: "Khoảng cách giữa các phần tử." },
        { name: "children", type: "content | relative | fraction", positional: true, desc: "Phần tử + khoảng cách xen kẽ (biến thiên ..)." },
      ],
      examples: [`#stack(dir: ttb, spacing: 8pt, [A], [B], [C])`],
      paramExamples: [
        { caption: "dir + spacing — xếp ngang", snapshotId: "layout-stack-dir", code: `#stack(
  dir: ltr,
  spacing: 1em,
  rect(width: 1cm, height: 1cm, fill: red),
  rect(width: 1cm, height: 1cm, fill: green),
  rect(width: 1cm, height: 1cm, fill: blue),
)` },
      ],
    },
    {
      name: "place",
      slug: "place",
      kind: "function",
      signature: "place(alignment, scope, float, clearance, dx, dy, body)",
      summary: "Đặt nội dung tương đối so với vùng chứa cha (góc trang, nổi...).",
      docUrl: `${DOC}place/`,
      snapshotId: "layout-place",
      params: [
        { name: "alignment", type: "auto | alignment", default: "start", positional: true, desc: "Vị trí đặt (vd top + right)." },
        { name: "scope", type: "str", default: '"column"', settable: true, desc: '"column" hoặc "parent".' },
        { name: "float", type: "bool", default: "false", settable: true, desc: "Cho nội dung nổi lên đầu/cuối." },
        { name: "clearance", type: "length", default: "1.5em", settable: true, desc: "Khoảng cách tối thiểu khi float." },
        { name: "dx", type: "relative", default: "0pt", settable: true, desc: "Dịch ngang." },
        { name: "dy", type: "relative", default: "0pt", settable: true, desc: "Dịch dọc." },
        { name: "body", type: "content", positional: true, desc: "Nội dung cần đặt." },
      ],
      examples: [`#place(top + right, dx: -1cm)[Góc phải trên]`],
      paramExamples: [
        { caption: "alignment + dx/dy — đặt vào góc vùng chứa", snapshotId: "layout-place-align", width: "300pt", code: `#block(width: 100%, height: 2.5cm, stroke: 0.5pt)[
  #place(top + right, dx: -4pt, dy: 4pt)[Góc phải trên]
  #place(bottom + left, dx: 4pt, dy: -4pt)[Góc trái dưới]
]` },
      ],
    },
    {
      name: "block",
      slug: "block",
      kind: "element",
      signature: "block(width, height, breakable, fill, stroke, radius, inset, outset, spacing, above, below, clip, sticky, body)",
      summary: "Vùng chứa cấp khối (block-level) cho nội dung; có thể tô nền, viền, đệm.",
      docUrl: `${DOC}block/`,
      snapshotId: "layout-block",
      params: [
        { name: "width", type: "auto | relative", default: "auto", settable: true, desc: "Chiều rộng khối." },
        { name: "height", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều cao khối." },
        { name: "breakable", type: "bool", default: "true", settable: true, desc: "Cho phép ngắt qua trang." },
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu nền." },
        { name: "stroke", type: SHAPE_STROKE, default: "none", settable: true, desc: "Nét viền." },
        { name: "radius", type: "relative | dictionary", default: "(:)", settable: true, desc: "Bo góc." },
        { name: "inset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Đệm trong." },
        { name: "outset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Nới ngoài." },
        { name: "spacing", type: "relative | fraction", default: "1.2em", settable: true, desc: "Khoảng cách trên/dưới." },
        { name: "clip", type: "bool", default: "false", settable: true, desc: "Cắt nội dung tràn." },
        { name: "body", type: "none | content", default: "none", positional: true, desc: "Nội dung khối." },
      ],
      examples: [`#block(fill: blue.lighten(85%), inset: 8pt, radius: 4pt)[Khối]`],
      paramExamples: [
        { caption: "fill + stroke + radius + inset — khối có khung", snapshotId: "layout-block-style", width: "300pt", code: `#block(
  fill: blue.lighten(80%),
  stroke: 1pt + blue,
  radius: 6pt,
  inset: 10pt,
)[Khối có nền, viền và bo góc.]` },
      ],
    },
    {
      name: "box",
      slug: "box",
      kind: "element",
      signature: "box(width, height, baseline, fill, stroke, radius, inset, outset, clip, body)",
      summary: "Vùng chứa cấp dòng (inline) định kích thước, đặt được trong đoạn văn.",
      docUrl: `${DOC}box/`,
      snapshotId: "layout-box",
      params: [
        { name: "width", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều rộng." },
        { name: "height", type: "auto | relative", default: "auto", settable: true, desc: "Chiều cao." },
        { name: "baseline", type: "relative", default: "0%", settable: true, desc: "Dời đường cơ sở." },
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu nền." },
        { name: "stroke", type: SHAPE_STROKE, default: "none", settable: true, desc: "Nét viền." },
        { name: "radius", type: "relative | dictionary", default: "(:)", settable: true, desc: "Bo góc." },
        { name: "inset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Đệm trong." },
        { name: "outset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Nới ngoài." },
        { name: "clip", type: "bool", default: "false", settable: true, desc: "Cắt nội dung tràn." },
        { name: "body", type: "none | content", default: "none", positional: true, desc: "Nội dung trong hộp." },
      ],
      examples: [`Chữ #box(fill: yellow, inset: 2pt)[nổi bật] giữa dòng.`],
      paramExamples: [
        { caption: "fill + inset + radius — hộp nội dòng", snapshotId: "layout-box-fill", width: "320pt", code: `Một đoạn có #box(fill: yellow, inset: (x: 4pt, y: 2pt), radius: 3pt)[từ khóa] được tô nổi bật giữa dòng.` },
      ],
    },
    {
      name: "pad",
      slug: "pad",
      kind: "function",
      signature: "pad(left, top, right, bottom, x, y, rest, body)",
      summary: "Thêm khoảng đệm (padding) bao quanh nội dung.",
      docUrl: `${DOC}pad/`,
      snapshotId: "layout-pad",
      params: [
        { name: "left / right / top / bottom", type: "relative", default: "0% + 0pt", settable: true, desc: "Đệm từng cạnh." },
        { name: "x", type: "relative", default: "0% + 0pt", settable: true, desc: "Đệm trái + phải." },
        { name: "y", type: "relative", default: "0% + 0pt", settable: true, desc: "Đệm trên + dưới." },
        { name: "rest", type: "relative", default: "0% + 0pt", settable: true, desc: "Đệm cho các cạnh chưa đặt." },
        { name: "body", type: "content", positional: true, desc: "Nội dung được đệm." },
      ],
      examples: [`#pad(x: 2cm)[Đoạn thụt lề hai bên]`],
      paramExamples: [
        { caption: "x + y — đệm quanh nội dung", snapshotId: "layout-pad-demo", width: "300pt", code: `#block(stroke: 0.5pt)[
  #pad(x: 1cm, y: 8pt)[Nội dung được đệm bên trong khung.]
]` },
      ],
    },
    {
      name: "h",
      slug: "h",
      kind: "function",
      signature: "h(amount, weak)",
      summary: "Chèn khoảng trắng ngang trong đoạn văn (hỗ trợ fr để đẩy).",
      docUrl: `${DOC}h/`,
      snapshotId: "layout-h",
      params: [
        { name: "amount", type: "relative | fraction", positional: true, desc: "Lượng khoảng trắng (vd 1cm, 1fr)." },
        { name: "weak", type: "bool", default: "false", settable: true, desc: "Khoảng trắng yếu (gộp/bỏ ở mép)." },
      ],
      examples: [`Trái #h(1fr) Phải`],
      paramExamples: [
        { caption: "amount = 1fr — đẩy hai mép", snapshotId: "layout-h-fr", width: "300pt", code: `Trái #h(1fr) Giữa #h(1fr) Phải` },
      ],
    },
    {
      name: "v",
      slug: "v",
      kind: "function",
      signature: "v(amount, weak)",
      summary: "Chèn khoảng trắng dọc giữa các khối.",
      docUrl: `${DOC}v/`,
      snapshotId: "layout-v",
      params: [
        { name: "amount", type: "relative | fraction", positional: true, desc: "Lượng khoảng trắng dọc." },
        { name: "weak", type: "bool", default: "false", settable: true, desc: "Khoảng trắng yếu." },
      ],
      examples: [`Đoạn trên #v(1em) Đoạn dưới`],
    },
    {
      name: "pagebreak",
      slug: "pagebreak",
      kind: "function",
      signature: "pagebreak(weak, to)",
      summary: "Ngắt trang thủ công.",
      docUrl: `${DOC}pagebreak/`,
      params: [
        { name: "weak", type: "bool", default: "false", settable: true, desc: "Bỏ qua nếu trang hiện tại đang trống." },
        { name: "to", type: "none | str", default: "none", settable: true, desc: '"even"/"odd" để sang trang chẵn/lẻ.' },
      ],
      examples: [`#pagebreak()`],
    },
    {
      name: "colbreak",
      slug: "colbreak",
      kind: "function",
      signature: "colbreak(weak)",
      summary: "Buộc ngắt cột, đẩy nội dung sang cột tiếp theo.",
      docUrl: `${DOC}colbreak/`,
      params: [{ name: "weak", type: "bool", default: "false", settable: true, desc: "Bỏ qua nếu cột hiện tại trống." }],
      examples: [`#colbreak()`],
    },
    {
      name: "move",
      slug: "move",
      kind: "function",
      signature: "move(dx, dy, body)",
      summary: "Dịch chuyển nội dung mà không ảnh hưởng bố cục xung quanh.",
      docUrl: `${DOC}move/`,
      snapshotId: "layout-move",
      params: [
        { name: "dx", type: "relative", default: "0pt", settable: true, desc: "Dịch ngang." },
        { name: "dy", type: "relative", default: "0pt", settable: true, desc: "Dịch dọc." },
        { name: "body", type: "content", positional: true, desc: "Nội dung cần dịch." },
      ],
      examples: [`#move(dy: -3pt)[nhích lên]`],
    },
    {
      name: "rotate",
      slug: "rotate",
      kind: "function",
      signature: "rotate(angle, origin, reflow, body)",
      summary: "Quay nội dung quanh một điểm gốc.",
      docUrl: `${DOC}rotate/`,
      snapshotId: "layout-rotate",
      params: [
        { name: "angle", type: "angle", default: "0deg", positional: true, desc: "Góc quay." },
        { name: "origin", type: "alignment", default: "center + horizon", settable: true, desc: "Tâm quay." },
        { name: "reflow", type: "bool", default: "false", settable: true, desc: "Cho bố cục tính lại theo kích thước sau quay." },
        { name: "body", type: "content", positional: true, desc: "Nội dung cần quay." },
      ],
      examples: [`#rotate(30deg)[Nghiêng]`],
      paramExamples: [
        { caption: "angle + reflow — quay và tính lại chỗ", snapshotId: "layout-rotate-reflow", width: "300pt", code: `#box(inset: 6pt, stroke: 0.5pt)[#rotate(20deg, reflow: true)[Quay 20°]]` },
      ],
    },
    {
      name: "scale",
      slug: "scale",
      kind: "function",
      signature: "scale(factor, x, y, origin, reflow, body)",
      summary: "Phóng to/thu nhỏ nội dung.",
      docUrl: `${DOC}scale/`,
      snapshotId: "layout-scale",
      params: [
        { name: "factor", type: "auto | ratio", default: "100%", positional: true, desc: "Tỉ lệ cho cả hai trục." },
        { name: "x", type: "auto | ratio", default: "100%", settable: true, desc: "Tỉ lệ trục ngang." },
        { name: "y", type: "auto | ratio", default: "100%", settable: true, desc: "Tỉ lệ trục dọc." },
        { name: "origin", type: "alignment", default: "center + horizon", settable: true, desc: "Tâm phóng." },
        { name: "reflow", type: "bool", default: "false", settable: true, desc: "Cho bố cục tính lại kích thước." },
        { name: "body", type: "content", positional: true, desc: "Nội dung cần phóng." },
      ],
      examples: [`#scale(150%)[To gấp rưỡi]`],
      paramExamples: [
        { caption: "x + y — phóng khác nhau theo trục", snapshotId: "layout-scale-xy", width: "300pt", code: `#box(inset: 6pt)[#scale(x: 160%, y: 80%, reflow: true)[Kéo giãn]]` },
      ],
    },
    {
      name: "skew",
      slug: "skew",
      kind: "function",
      signature: "skew(ax, ay, origin, reflow, body)",
      summary: "Làm xiên (skew) nội dung theo trục ngang/dọc.",
      docUrl: `${DOC}skew/`,
      snapshotId: "layout-skew",
      params: [
        { name: "ax", type: "angle", default: "0deg", settable: true, desc: "Góc xiên theo trục ngang." },
        { name: "ay", type: "angle", default: "0deg", settable: true, desc: "Góc xiên theo trục dọc." },
        { name: "origin", type: "alignment", default: "center + horizon", settable: true, desc: "Tâm biến hình." },
        { name: "reflow", type: "bool", default: "false", settable: true, desc: "Cho bố cục tính lại." },
        { name: "body", type: "content", positional: true, desc: "Nội dung cần làm xiên." },
      ],
      examples: [`#skew(ax: 20deg)[Xiên]`],
    },
    {
      name: "repeat",
      slug: "repeat",
      kind: "function",
      signature: "repeat(gap, justify, body)",
      summary: "Lặp nội dung lấp đầy khoảng trống (vd chấm dẫn trong mục lục).",
      docUrl: `${DOC}repeat/`,
      snapshotId: "layout-repeat",
      params: [
        { name: "gap", type: "length", default: "0pt", settable: true, desc: "Khoảng cách giữa các lần lặp." },
        { name: "justify", type: "bool", default: "true", settable: true, desc: "Giãn đều để lấp kín." },
        { name: "body", type: "content", positional: true, desc: "Nội dung được lặp." },
      ],
      examples: [`Chương 1 #box(width: 1fr, repeat[.]) 5`],
      paramExamples: [
        { caption: "gap — chấm dẫn kiểu mục lục", snapshotId: "layout-repeat-gap", width: "300pt", code: `Chương 1. Mở đầu #box(width: 1fr, repeat(gap: 3pt)[.]) 5` },
      ],
    },
    {
      name: "hide",
      slug: "hide",
      kind: "function",
      signature: "hide(body)",
      summary: "Ẩn nội dung nhưng vẫn giữ chỗ trong bố cục.",
      docUrl: `${DOC}hide/`,
      snapshotId: "layout-hide",
      params: [{ name: "body", type: "content", positional: true, desc: "Nội dung cần ẩn (giữ chỗ)." }],
      examples: [`#hide[văn bản vô hình nhưng chiếm chỗ]`],
    },
    {
      name: "measure",
      slug: "measure",
      kind: "function",
      signature: "measure(content)",
      summary: "Đo kích thước thực tế của nội dung sau khi bố cục (cần context).",
      docUrl: `${DOC}measure/`,
      params: [{ name: "content", type: "content", positional: true, desc: "Nội dung cần đo; trả về dict {width, height}." }],
      examples: [`#context measure([Xin chào]).width`],
    },
    {
      name: "layout",
      slug: "layout",
      kind: "function",
      signature: "layout(func)",
      summary: "Truy cập kích thước vùng chứa bao ngoài để tính toán bố cục động.",
      docUrl: `${DOC}layout/`,
      params: [{ name: "func", type: "function", positional: true, desc: "Hàm nhận size (rộng/cao) và trả về nội dung." }],
      examples: [`#layout(size => [Rộng: #size.width])`],
    },
    {
      name: "alignment",
      slug: "alignment",
      kind: "type",
      signature: "left · center · right · top · horizon · bottom · start · end",
      summary: "Kiểu vị trí căn lề dọc theo một trục; kết hợp bằng + (vd top + right).",
      docUrl: `${DOC}alignment/`,
      snapshotId: "layout-alignment",
      params: [
        { name: "Ngang", type: "alignment", desc: "start, end, left, center, right." },
        { name: "Dọc", type: "alignment", desc: "top, horizon, bottom." },
        { name: ".axis() / .inv()", type: "method", desc: "Lấy trục / đảo chiều căn." },
      ],
      examples: [`#align(center + horizon)[Giữa hoàn toàn]`],
    },
    {
      name: "angle",
      slug: "angle",
      kind: "type",
      signature: "1deg · 1rad",
      summary: "Kiểu góc (đơn vị deg hoặc rad).",
      docUrl: `${DOC}angle/`,
      snapshotId: "layout-angle",
      params: [
        { name: "deg / rad", type: "đơn vị", desc: "Độ và radian." },
        { name: ".deg() / .rad()", type: "method", desc: "Chuyển đổi sang số đo tương ứng." },
      ],
      examples: [`#rotate(45deg)[…]`],
    },
    {
      name: "length",
      slug: "length",
      kind: "type",
      signature: "1pt · 1mm · 1cm · 1in · 1em",
      summary: "Kiểu độ dài/kích thước; em phụ thuộc cỡ chữ.",
      docUrl: `${DOC}length/`,
      params: [
        { name: "pt / mm / cm / in", type: "đơn vị tuyệt đối", desc: "Điểm, milimet, centimet, inch." },
        { name: "em", type: "đơn vị tương đối", desc: "Theo cỡ chữ hiện tại." },
      ],
      examples: [`#set text(size: 12pt)`],
    },
    {
      name: "ratio",
      slug: "ratio",
      kind: "type",
      signature: "50%",
      summary: "Kiểu tỉ lệ phần trăm của một tổng thể.",
      docUrl: `${DOC}ratio/`,
      snapshotId: "layout-ratio",
      params: [{ name: "%", type: "đơn vị", desc: "Phần trăm." }],
      examples: [`#image("a.png", width: 80%)`],
    },
    {
      name: "relative",
      slug: "relative",
      kind: "type",
      signature: "50% + 1cm",
      summary: "Độ dài tương đối = phần trăm + độ dài tuyệt đối.",
      docUrl: `${DOC}relative/`,
      params: [{ name: "ratio + length", type: "tổ hợp", desc: "Kết hợp tỉ lệ và độ dài cố định." }],
      examples: [`#pad(x: 10% + 1cm)[…]`],
    },
    {
      name: "fraction",
      slug: "fraction",
      kind: "type",
      signature: "1fr",
      summary: "Kiểu phân số (fr) — phân bổ phần không gian còn lại.",
      docUrl: `${DOC}fraction/`,
      snapshotId: "layout-fraction",
      params: [{ name: "fr", type: "đơn vị", desc: "Chia không gian trống theo tỉ lệ." }],
      examples: [`#grid(columns: (1fr, 2fr), [a], [b])`],
    },
    {
      name: "direction",
      slug: "direction",
      kind: "type",
      signature: "ltr · rtl · ttb · btt",
      summary: "Kiểu hướng bố cục (trái-phải / phải-trái / trên-dưới / dưới-trên).",
      docUrl: `${DOC}direction/`,
      snapshotId: "layout-direction",
      params: [
        { name: "ltr / rtl", type: "ngang", desc: "Trái→phải / phải→trái." },
        { name: "ttb / btt", type: "dọc", desc: "Trên→dưới / dưới→trên." },
      ],
      examples: [`#stack(dir: ltr, [a], [b])`],
    },
  ],
};
