import { Sigma } from "lucide-react";
import type { ReferenceCategory } from "./types";

const DOC = "https://typst.app/docs/reference/math/";

export const math: ReferenceCategory = {
  slug: "math",
  title: "Toán học (Math)",
  icon: Sigma,
  summary: "Công thức toán: phân số, ma trận, vector, hệ điều kiện, dấu phụ, chỉ số trên/dưới, căn, toán tử và biến thể kiểu chữ.",
  docUrl: DOC,
  fns: [
    {
      name: "equation",
      slug: "equation",
      kind: "element",
      signature: "equation(block, numbering, number-align, supplement, body)",
      summary: "Một phương trình toán; gốc của mọi nội dung math. Cú pháp ngắn: $...$ (nội dòng) / $ ... $ (khối).",
      docUrl: `${DOC}equation/`,
      snapshotId: "math-equation",
      params: [
        { name: "block", type: "bool", default: "false", settable: true, desc: "Hiển thị dạng khối (true) hay nội dòng (false)." },
        { name: "numbering", type: "none | str | function", default: "none", settable: true, desc: 'Đánh số phương trình, vd "(1)".' },
        { name: "number-align", type: "alignment", default: "end + horizon", settable: true, desc: "Vị trí số phương trình." },
        { name: "supplement", type: "none | auto | content", default: "auto", settable: true, desc: 'Tiền tố tham chiếu (vd "Phương trình").' },
        { name: "body", type: "content", positional: true, desc: "Nội dung công thức." },
      ],
      examples: [`$ a^2 + b^2 = c^2 $`, `Nội dòng: $x^2$.`],
      paramExamples: [
        { caption: "numbering — đánh số phương trình", snapshotId: "math-equation-numbering", width: "300pt", code: `#set math.equation(numbering: "(1)")
$ a^2 + b^2 = c^2 $` },
      ],
    },
    {
      name: "frac",
      slug: "frac",
      kind: "function",
      signature: "frac(num, denom)",
      summary: "Phân số. Cú pháp ngắn trong math: a/b.",
      docUrl: `${DOC}frac/`,
      snapshotId: "math-frac",
      params: [
        { name: "num", type: "content", positional: true, desc: "Tử số." },
        { name: "denom", type: "content", positional: true, desc: "Mẫu số." },
      ],
      examples: [`$ frac(a + b, c) $`, `$ (a + b) / c $`],
    },
    {
      name: "mat",
      slug: "mat",
      kind: "function",
      signature: "mat(delim, align, gap, row-gap, column-gap, augment, ..rows)",
      summary: "Ma trận; dùng dấu , ngăn cột và ; ngăn hàng.",
      docUrl: `${DOC}mat/`,
      snapshotId: "math-mat",
      params: [
        { name: "delim", type: "none | str | array", default: '"("', settable: true, desc: 'Cặp dấu phân cách: "(", "[", "{", "|"...' },
        { name: "align", type: "alignment", default: "center", settable: true, desc: "Căn lề phần tử trong ô." },
        { name: "gap", type: "relative", default: "0pt", settable: true, desc: "Khoảng cách hàng và cột (chung)." },
        { name: "augment", type: "none | int | dictionary", default: "none", settable: true, desc: "Vạch ngăn (ma trận khối/augmented)." },
        { name: "rows", type: "array", positional: true, desc: "Các hàng phần tử (biến thiên ..)." },
      ],
      examples: [`$ A = mat(1, 2; 3, 4) $`, `$ mat(delim: "[", 1, 0; 0, 1) $`],
      paramExamples: [
        { caption: "delim — đổi cặp dấu bao", snapshotId: "math-mat-delim", code: `$ mat(delim: "[", 1, 2; 3, 4) $` },
        { caption: "augment — vạch ngăn (ma trận khối)", snapshotId: "math-mat-augment", code: `$ mat(augment: #2, 1, 0, 0, 5; 0, 1, 0, 3; 0, 0, 1, 8) $` },
      ],
    },
    {
      name: "vec",
      slug: "vec",
      kind: "function",
      signature: "vec(delim, align, gap, ..children)",
      summary: "Vector cột (các phần tử xếp dọc).",
      docUrl: `${DOC}vec/`,
      snapshotId: "math-vec",
      params: [
        { name: "delim", type: "none | str | array", default: '"("', settable: true, desc: "Cặp dấu phân cách." },
        { name: "align", type: "alignment", default: "center", settable: true, desc: "Căn lề phần tử." },
        { name: "gap", type: "relative", default: "0.2em", settable: true, desc: "Khoảng cách giữa phần tử." },
        { name: "children", type: "content", positional: true, desc: "Các phần tử (biến thiên ..)." },
      ],
      examples: [`$ vec(1, 2, 3) $`],
      paramExamples: [
        { caption: "delim — đổi cặp dấu bao", snapshotId: "math-vec-delim", code: `$ vec(delim: "[", 1, 2, 3) $` },
      ],
    },
    {
      name: "cases",
      slug: "cases",
      kind: "function",
      signature: "cases(delim, reverse, gap, ..children)",
      summary: "Phân nhánh theo trường hợp, dùng ngoặc nhọn lớn.",
      docUrl: `${DOC}cases/`,
      snapshotId: "math-cases",
      params: [
        { name: "delim", type: "none | str | array", default: '"{"', settable: true, desc: "Dấu phân cách bao ngoài." },
        { name: "reverse", type: "bool", default: "false", settable: true, desc: "Đặt dấu ngoặc bên phải." },
        { name: "gap", type: "relative", default: "0.2em", settable: true, desc: "Khoảng cách giữa các nhánh." },
        { name: "children", type: "content", positional: true, desc: "Các nhánh (biến thiên ..)." },
      ],
      examples: [`$ f(x) = cases(x "nếu" x >= 0, -x "ngược lại") $`],
      paramExamples: [
        { caption: "reverse — đặt ngoặc bên phải", snapshotId: "math-cases-reverse", code: `$ cases(reverse: #true, a, b, c) = x $` },
      ],
    },
    {
      name: "accent",
      slug: "accent",
      kind: "function",
      signature: "accent(base, accent, size)",
      summary: "Gắn dấu phụ lên ký hiệu. Lối tắt: hat(x), tilde(x), dot(x), bar(x), arrow(x)...",
      docUrl: `${DOC}accent/`,
      snapshotId: "math-accent",
      params: [
        { name: "base", type: "content", positional: true, desc: "Ký hiệu cơ sở." },
        { name: "accent", type: "str | content", positional: true, desc: "Dấu phụ (vd hat, tilde, dot, arrow)." },
        { name: "size", type: "auto | relative", default: "auto", settable: true, desc: "Bề rộng dấu phụ." },
      ],
      examples: [`$ hat(x) quad tilde(y) quad arrow(v) quad dot(z) $`],
    },
    {
      name: "attach",
      slug: "attach",
      kind: "function",
      signature: "attach(base, t, b, tl, tr, bl, br)",
      summary: "Gắn chỉ số trên/dưới và các góc. Lối tắt: x^2 (trên), x_i (dưới).",
      docUrl: `${DOC}attach/`,
      snapshotId: "math-attach",
      params: [
        { name: "base", type: "content", positional: true, desc: "Biểu thức cơ sở." },
        { name: "t / b", type: "content", desc: "Chỉ số trên (top) / dưới (bottom)." },
        { name: "tl / tr / bl / br", type: "content", desc: "Các góc trên-trái/trên-phải/dưới-trái/dưới-phải." },
      ],
      examples: [`$ x_1^2 quad sum_(i=1)^n x_i $`, `$ attach(F, tl: 1, bl: 2, tr: 3) $`],
    },
    {
      name: "root",
      slug: "root",
      kind: "function",
      signature: "root(index, radicand)   ·   sqrt(radicand)",
      summary: "Căn bậc hai (sqrt) và căn bậc n (root).",
      docUrl: `${DOC}roots/`,
      snapshotId: "math-root",
      params: [
        { name: "index", type: "none | content", desc: "Bậc của căn (vd 3 cho căn bậc ba)." },
        { name: "radicand", type: "content", positional: true, desc: "Biểu thức dưới dấu căn." },
      ],
      examples: [`$ sqrt(x + 1) quad root(3, x) $`],
    },
    {
      name: "binom",
      slug: "binom",
      kind: "function",
      signature: "binom(upper, ..lower)",
      summary: "Hệ số nhị thức (tổ hợp), tử trên mẫu trong ngoặc.",
      docUrl: `${DOC}binom/`,
      snapshotId: "math-binom",
      params: [
        { name: "upper", type: "content", positional: true, desc: "Phần trên." },
        { name: "lower", type: "content", positional: true, desc: "Phần dưới (một hoặc nhiều, biến thiên ..)." },
      ],
      examples: [`$ binom(n, k) $`],
    },
    {
      name: "op",
      slug: "op",
      kind: "function",
      signature: "op(text, limits)",
      summary: "Toán tử dạng chữ (sin, lim, max...), tùy chọn đặt giới hạn trên/dưới.",
      docUrl: `${DOC}op/`,
      snapshotId: "math-op",
      params: [
        { name: "text", type: "content", positional: true, desc: "Tên toán tử." },
        { name: "limits", type: "bool", default: "false", settable: true, desc: "Đặt chỉ số ngay trên/dưới (như lim/sum)." },
      ],
      examples: [`$ lim_(x -> 0) (sin x)/x = 1 $`, `$ op("argmax", limits: true)_x f(x) $`],
    },
    {
      name: "lr",
      slug: "lr",
      kind: "function",
      signature: "lr(body, size)   ·   abs(), norm(), floor(), ceil(), round()",
      summary: "Co giãn cặp dấu phân cách theo chiều cao nội dung; gồm abs/norm/floor/ceil.",
      docUrl: `${DOC}lr/`,
      snapshotId: "math-lr",
      params: [
        { name: "body", type: "content", positional: true, desc: "Nội dung kèm cặp dấu hai đầu." },
        { name: "size", type: "auto | relative", default: "auto", settable: true, desc: "Ép kích thước dấu phân cách." },
      ],
      examples: [`$ abs((a)/(b)) quad norm(v) quad floor(x) $`],
    },
    {
      name: "cancel",
      slug: "cancel",
      kind: "function",
      signature: "cancel(body, length, inverted, cross, angle, stroke)",
      summary: "Vẽ đường gạch chéo lên biểu thức (biểu thị khử/rút gọn).",
      docUrl: `${DOC}cancel/`,
      snapshotId: "math-cancel",
      params: [
        { name: "body", type: "content", positional: true, desc: "Biểu thức bị gạch." },
        { name: "length", type: "relative", default: "100% + 3pt", settable: true, desc: "Độ dài nét gạch." },
        { name: "inverted", type: "bool", default: "false", settable: true, desc: "Đảo chiều nét gạch." },
        { name: "cross", type: "bool", default: "false", settable: true, desc: "Gạch chéo hai nét (chữ X)." },
        { name: "stroke", type: "stroke", default: "0.5pt", settable: true, desc: "Kiểu nét gạch." },
      ],
      examples: [`$ (cancel(x) dot y) / cancel(x) = y $`],
      paramExamples: [
        { caption: "cross + inverted — kiểu nét gạch", snapshotId: "math-cancel-cross", code: `$ cancel(x, cross: #true) quad cancel(y, inverted: #true) $` },
      ],
    },
    {
      name: "underover",
      slug: "underover",
      kind: "function",
      signature: "underbrace · overbrace · underline · overline · underbracket · overbracket",
      summary: "Đặt dấu ngoặc nhọn/gạch/ngoặc vuông phía trên hoặc dưới một biểu thức.",
      docUrl: `${DOC}underover/`,
      snapshotId: "math-underover",
      params: [
        { name: "body", type: "content", positional: true, desc: "Biểu thức cơ sở." },
        { name: "annotation", type: "content", positional: true, desc: "Chú thích đi kèm (tùy hàm)." },
      ],
      examples: [`$ underbrace(1 + 2 + 3, "ba số") quad overline(A B) $`],
    },
    {
      name: "variants",
      slug: "variants",
      kind: "function",
      signature: "serif · sans · cal · frak · mono · bb · upright · italic · bold",
      summary: "Chọn biến thể kiểu chữ trong công thức (sans, hoa mỹ, Fraktur, mono, bảng đen...).",
      docUrl: `${DOC}variants/`,
      snapshotId: "math-variants",
      params: [
        { name: "body", type: "content", positional: true, desc: "Nội dung đổi kiểu chữ." },
      ],
      examples: [`$ cal(F) quad frak(g) quad bb(R) quad sans(x) quad bold(v) $`],
    },
    {
      name: "class",
      slug: "class",
      kind: "function",
      signature: "class(class, body)",
      summary: "Ép một biểu thức dùng lớp toán học nhất định (ảnh hưởng khoảng cách).",
      docUrl: `${DOC}class/`,
      params: [
        { name: "class", type: "str", positional: true, desc: '"normal", "binary", "relation", "unary", "opening", "closing"...' },
        { name: "body", type: "content", positional: true, desc: "Biểu thức áp lớp." },
      ],
      examples: [`$ class("binary", star) $`],
    },
    {
      name: "primes",
      slug: "primes",
      kind: "function",
      signature: "primes(count)",
      summary: "Nhóm dấu phẩy lũy thừa (prime) trên ký hiệu.",
      docUrl: `${DOC}primes/`,
      snapshotId: "math-primes",
      params: [{ name: "count", type: "int", positional: true, desc: "Số dấu phẩy (1, 2, 3...)." }],
      examples: [`$ f'(x) quad f''(x) $`],
    },
    {
      name: "stretch",
      slug: "stretch",
      kind: "function",
      signature: "stretch(body, size)",
      summary: "Kéo giãn một glyph (vd mũi tên, dấu ngoặc) theo kích thước.",
      docUrl: `${DOC}stretch/`,
      snapshotId: "math-stretch",
      params: [
        { name: "body", type: "content", positional: true, desc: "Glyph cần kéo giãn." },
        { name: "size", type: "relative", default: "100%", settable: true, desc: "Kích thước đích." },
      ],
      examples: [`$ stretch(->, size: #2em) $`],
    },
    {
      name: "sizes",
      slug: "sizes",
      kind: "function",
      signature: "display · inline · script · sscript",
      summary: "Ép kiểu kích thước hiển thị cho biểu thức (display/inline/script/sscript).",
      docUrl: `${DOC}sizes/`,
      snapshotId: "math-sizes",
      params: [
        { name: "body", type: "content", positional: true, desc: "Biểu thức cần ép cỡ." },
        { name: "cramped", type: "bool", default: "false", settable: true, desc: "Chế độ cramped (hạ chỉ số trên)." },
      ],
      examples: [`$ display(sum_(i=1)^n) quad inline(sum_(i=1)^n) $`],
    },
    {
      name: "sym",
      slug: "sym",
      kind: "module",
      signature: "module sym  ·  pi, dot, RR, arrow.r, lt.eq ...",
      summary: "Mô-đun ký hiệu (1198 ký hiệu trong Typst v0.14.2) dùng trực tiếp trong math mode; xem nhóm Ký hiệu.",
      docUrl: "https://typst.app/docs/reference/symbols/sym/",
      snapshotId: "math-sym",
      params: [
        { name: "Chữ Hy Lạp", type: "symbol", desc: "alpha, beta, ... pi, Omega." },
        { name: "Tập số", type: "symbol", desc: "RR, NN, ZZ, QQ, CC." },
        { name: "Quan hệ/toán tử", type: "symbol", desc: "lt.eq, gt.eq, eq.not, times, dot, in, subset." },
        { name: "Mũi tên", type: "symbol", desc: "arrow.r, arrow.l, arrow.r.double..." },
      ],
      examples: [`$ alpha + pi r^2 <= RR $`],
    },
  ],
};
