import { ListTree } from "lucide-react";
import type { ReferenceCategory } from "./types";

const DOC = "https://typst.app/docs/reference/model/";
const CELL_STROKE = "none | length | color | gradient | stroke | tiling | array | dictionary | function";
const TRACK = "auto | int | relative | fraction | array";

export const model: ReferenceCategory = {
  slug: "model",
  title: "Nội dung (Model)",
  icon: ListTree,
  summary: "Phần tử cấu trúc tài liệu: tiêu đề, danh sách, bảng, hình, mục lục, trích dẫn và tài liệu tham khảo.",
  docUrl: DOC,
  fns: [
    {
      name: "heading",
      slug: "heading",
      kind: "element",
      signature: "heading(level, depth, offset, numbering, supplement, outlined, bookmarked, hanging-indent, body)",
      summary: "Tiêu đề mục/phần. Cú pháp ngắn: = Tiêu đề (==, === cho cấp sâu hơn).",
      docUrl: `${DOC}heading/`,
      snapshotId: "model-heading",
      params: [
        { name: "level", type: "auto | int", default: "auto", settable: true, desc: "Cấp tuyệt đối; auto = tính theo depth + offset." },
        { name: "depth", type: "int", default: "1", settable: true, desc: "Cấp tương đối (số dấu = trong markup)." },
        { name: "offset", type: "int", default: "0", settable: true, desc: "Độ lệch cấp cộng thêm." },
        { name: "numbering", type: "none | str | function", default: "none", settable: true, desc: 'Kiểu đánh số tiêu đề, vd "1.1.1".' },
        { name: "supplement", type: "none | auto | content | function", default: "auto", settable: true, desc: 'Tiền tố khi tham chiếu (vd "Mục").' },
        { name: "outlined", type: "bool", default: "true", settable: true, desc: "Có xuất hiện trong mục lục không." },
        { name: "bookmarked", type: "auto | bool", default: "auto", settable: true, desc: "Có tạo bookmark PDF không." },
        { name: "hanging-indent", type: "auto | length", default: "auto", settable: true, desc: "Thụt treo phần nội dung sau số thứ tự." },
        { name: "body", type: "content", positional: true, desc: "Nội dung tiêu đề." },
      ],
      examples: [`#set heading(numbering: "1.1")
= Chương một
== Mục con`],
      paramExamples: [
        { caption: "numbering — đánh số tiêu đề", snapshotId: "model-heading-numbering", width: "300pt", code: `#set heading(numbering: "1.1")
= Chương một
== Mục con
=== Tiểu mục` },
      ],
    },
    {
      name: "list",
      slug: "list",
      kind: "element",
      signature: "list(tight, marker, indent, body-indent, spacing, ..children)",
      summary: "Danh sách dấu đầu dòng (bullet). Cú pháp ngắn: - mục.",
      docUrl: `${DOC}list/`,
      snapshotId: "model-list",
      params: [
        { name: "tight", type: "bool", default: "true", settable: true, desc: "Khoảng cách dòng sát nhau (true) hay theo đoạn." },
        { name: "marker", type: "content | array | function", default: "[•]", settable: true, desc: "Dấu đầu dòng; mảng để đổi theo cấp." },
        { name: "indent", type: "length", default: "0pt", settable: true, desc: "Thụt lề toàn danh sách." },
        { name: "body-indent", type: "length", default: "0.5em", settable: true, desc: "Khoảng cách từ dấu tới nội dung." },
        { name: "spacing", type: "auto | relative", default: "auto", settable: true, desc: "Khoảng cách giữa các mục (khi không tight)." },
        { name: "children", type: "content", positional: true, desc: "Các mục danh sách (biến thiên ..)." },
      ],
      examples: [`- Mục thứ nhất
- Mục thứ hai`],
      paramExamples: [
        { caption: "marker — đổi dấu đầu dòng", snapshotId: "model-list-marker", width: "300pt", code: `#list(marker: [→])[Mục một][Mục hai][Mục ba]` },
      ],
      members: [
        {
          name: "list.item", slug: "list.item", kind: "function",
          signature: "list.item(body)",
          summary: "Một mục trong danh sách dấu đầu dòng.",
          docUrl: `${DOC}list/#definitions-item`,
          params: [{ name: "body", type: "content", positional: true, desc: "Nội dung mục." }],
        },
      ],
    },
    {
      name: "enum",
      slug: "enum",
      kind: "element",
      signature: "enum(tight, numbering, start, full, reversed, indent, body-indent, spacing, number-align, ..children)",
      summary: "Danh sách có đánh số. Cú pháp ngắn: + mục (hoặc 1. mục).",
      docUrl: `${DOC}enum/`,
      snapshotId: "model-enum",
      params: [
        { name: "tight", type: "bool", default: "true", settable: true, desc: "Khoảng cách dòng sát nhau." },
        { name: "numbering", type: "str | function", default: '"1."', settable: true, desc: 'Kiểu đánh số, vd "1.", "a)", "i.".' },
        { name: "start", type: "auto | int", default: "auto", settable: true, desc: "Số bắt đầu." },
        { name: "full", type: "bool", default: "false", settable: true, desc: "Truyền toàn bộ số cha vào hàm numbering." },
        { name: "reversed", type: "bool", default: "false", settable: true, desc: "Đánh số ngược." },
        { name: "indent", type: "length", default: "0pt", settable: true, desc: "Thụt lề danh sách." },
        { name: "body-indent", type: "length", default: "0.5em", settable: true, desc: "Khoảng cách từ số tới nội dung." },
        { name: "spacing", type: "auto | relative", default: "auto", settable: true, desc: "Khoảng cách giữa các mục." },
        { name: "number-align", type: "alignment", default: "end + top", settable: true, desc: "Căn lề số thứ tự." },
        { name: "children", type: "content", positional: true, desc: "Các mục (biến thiên ..)." },
      ],
      examples: [`+ Bước một
+ Bước hai`],
      paramExamples: [
        { caption: "numbering — kiểu đánh số", snapshotId: "model-enum-numbering", width: "300pt", code: `#enum(numbering: "a)")[Mục đầu][Mục sau][Mục cuối]` },
        { caption: "start — số bắt đầu", snapshotId: "model-enum-start", width: "300pt", code: `#enum(start: 5)[Năm][Sáu][Bảy]` },
      ],
      members: [
        {
          name: "enum.item", slug: "enum.item", kind: "function",
          signature: "enum.item(number, body)",
          summary: "Một mục trong danh sách đánh số (có thể chỉ định số).",
          docUrl: `${DOC}enum/#definitions-item`,
          params: [
            { name: "number", type: "none | int", default: "none", desc: "Số thứ tự chỉ định (none = tự động)." },
            { name: "body", type: "content", positional: true, desc: "Nội dung mục." },
          ],
        },
      ],
    },
    {
      name: "terms",
      slug: "terms",
      kind: "element",
      signature: "terms(tight, separator, indent, hanging-indent, spacing, ..children)",
      summary: "Danh sách định nghĩa (thuật ngữ + mô tả). Cú pháp ngắn: / Thuật ngữ: mô tả.",
      docUrl: `${DOC}terms/`,
      snapshotId: "model-terms",
      params: [
        { name: "tight", type: "bool", default: "true", settable: true, desc: "Khoảng cách dòng sát nhau." },
        { name: "separator", type: "content", default: "khoảng trắng đậm", settable: true, desc: "Dấu ngăn giữa thuật ngữ và mô tả." },
        { name: "indent", type: "length", default: "0pt", settable: true, desc: "Thụt lề danh sách." },
        { name: "hanging-indent", type: "length", default: "2em", settable: true, desc: "Thụt treo phần mô tả." },
        { name: "spacing", type: "auto | relative", default: "auto", settable: true, desc: "Khoảng cách giữa các mục." },
        { name: "children", type: "array | content", positional: true, desc: "Các cặp (thuật ngữ, mô tả)." },
      ],
      examples: [`/ Typst: ngôn ngữ soạn thảo
/ PDF: định dạng xuất bản`],
      paramExamples: [
        { caption: "separator — dấu ngăn thuật ngữ/mô tả", snapshotId: "model-terms-separator", width: "320pt", code: `#set terms(separator: [ — ])
/ Typst: ngôn ngữ soạn thảo
/ PDF: định dạng xuất bản` },
      ],
      members: [
        {
          name: "terms.item", slug: "terms.item", kind: "function",
          signature: "terms.item(term, description)",
          summary: "Một mục thuật ngữ + mô tả trong danh sách định nghĩa.",
          docUrl: `${DOC}terms/#definitions-item`,
          params: [
            { name: "term", type: "content", positional: true, desc: "Thuật ngữ." },
            { name: "description", type: "content", positional: true, desc: "Phần mô tả/giải nghĩa." },
          ],
        },
      ],
    },
    {
      name: "table",
      slug: "table",
      kind: "element",
      signature: "table(columns, rows, gutter, column-gutter, row-gutter, inset, align, fill, stroke, ..children)",
      summary: "Bảng dữ liệu nhiều hàng/cột. Kèm table.header, table.footer, table.cell, table.hline, table.vline.",
      docUrl: `${DOC}table/`,
      snapshotId: "model-table",
      params: [
        { name: "columns", type: TRACK, default: "()", settable: true, desc: "Số/kích thước cột (xem grid)." },
        { name: "rows", type: TRACK, default: "()", settable: true, desc: "Số/kích thước hàng." },
        { name: "gutter", type: TRACK, default: "()", settable: true, desc: "Khoảng hở chung giữa các ô." },
        { name: "column-gutter", type: TRACK, default: "()", settable: true, desc: "Khoảng hở giữa cột (ưu tiên hơn gutter)." },
        { name: "row-gutter", type: TRACK, default: "()", settable: true, desc: "Khoảng hở giữa hàng." },
        { name: "inset", type: "relative | array | dictionary | function", default: "0% + 5pt", settable: true, desc: "Đệm bên trong ô." },
        { name: "align", type: "auto | array | alignment | function", default: "auto", settable: true, desc: "Căn lề nội dung trong ô." },
        { name: "fill", type: "none | color | gradient | tiling | array | function", default: "none", settable: true, desc: "Màu nền ô (hàm để tạo sọc)." },
        { name: "stroke", type: CELL_STROKE, default: "1pt + black", settable: true, desc: "Nét kẻ ô; none để bỏ." },
        { name: "children", type: "content", positional: true, desc: "Nội dung các ô (+ hline/vline), biến thiên .." },
      ],
      examples: [`#table(
  columns: 3,
  table.header[STT][Tên][Điểm],
  [1], [Nguyễn Văn A], [9.0],
)`],
      paramExamples: [
        { caption: "fill + align — nền hàng tiêu đề + căn giữa", snapshotId: "model-table-fill", width: "320pt", code: `#table(
  columns: 3,
  align: center,
  fill: (_, y) => if y == 0 { rgb("#cce5ff") },
  [STT], [Tên], [Điểm],
  [1], [An], [9.0],
)` },
        { caption: "stroke — bỏ toàn bộ nét kẻ", snapshotId: "model-table-stroke", width: "320pt", code: `#table(
  columns: 2,
  stroke: none,
  [Họ tên], [Lớp],
  [Nguyễn Văn A], [CNTT1],
)` },
      ],
      members: [
        {
          name: "table.cell", slug: "table.cell", kind: "function",
          signature: "table.cell(x, y, colspan, rowspan, fill, align, inset, stroke, breakable, body)",
          summary: "Ô bảng tuỳ biến: gộp ô, đổi màu/căn lề/nét riêng cho một ô.",
          docUrl: `${DOC}table/#definitions-cell`,
          params: [
            { name: "x", type: "auto | int", default: "auto", desc: "Chỉ số cột (0-based)." },
            { name: "y", type: "auto | int", default: "auto", desc: "Chỉ số hàng (0-based)." },
            { name: "colspan", type: "int", default: "1", desc: "Số cột ô chiếm." },
            { name: "rowspan", type: "int", default: "1", desc: "Số hàng ô chiếm." },
            { name: "fill", type: "auto | none | color | gradient | tiling", default: "auto", desc: "Màu nền ô." },
            { name: "align", type: "auto | alignment", default: "auto", desc: "Căn lề nội dung ô." },
            { name: "inset", type: "auto | relative | dictionary", default: "auto", desc: "Đệm trong ô." },
            { name: "stroke", type: CELL_STROKE, default: "auto", desc: "Nét kẻ riêng cho ô." },
            { name: "breakable", type: "auto | bool", default: "auto", desc: "Cho ô ngắt qua trang." },
            { name: "body", type: "content", positional: true, desc: "Nội dung ô." },
          ],
          paramExamples: [
            { caption: "colspan — ô gộp nhiều cột", snapshotId: "model-tablecell-colspan", width: "320pt", code: `#table(
  columns: 3,
  table.cell(colspan: 3, fill: rgb("#cce5ff"))[Bảng điểm học kỳ],
  [1], [An], [9.0],
  [2], [Bình], [8.5],
)` },
          ],
        },
        {
          name: "table.header", slug: "table.header", kind: "function",
          signature: "table.header(repeat, level, ..children)",
          summary: "Nhóm hàng tiêu đề; tự lặp lại ở đầu mỗi trang.",
          docUrl: `${DOC}table/#definitions-header`,
          params: [
            { name: "repeat", type: "bool", default: "true", desc: "Lặp lại tiêu đề khi bảng sang trang." },
            { name: "level", type: "int", default: "1", desc: "Cấp tiêu đề (cho tiêu đề lồng nhau)." },
            { name: "children", type: "content", positional: true, desc: "Các ô tiêu đề (biến thiên ..)." },
          ],
        },
        {
          name: "table.footer", slug: "table.footer", kind: "function",
          signature: "table.footer(repeat, ..children)",
          summary: "Nhóm hàng chân bảng; tự lặp lại ở cuối mỗi trang.",
          docUrl: `${DOC}table/#definitions-footer`,
          params: [
            { name: "repeat", type: "bool", default: "true", desc: "Lặp lại ở mỗi trang." },
            { name: "children", type: "content", positional: true, desc: "Các ô chân bảng." },
          ],
        },
        {
          name: "table.hline", slug: "table.hline", kind: "function",
          signature: "table.hline(y, start, end, stroke, position)",
          summary: "Đường kẻ ngang tuỳ biến (vượt cả gutter).",
          docUrl: `${DOC}table/#definitions-hline`,
          params: [
            { name: "y", type: "auto | int", default: "auto", desc: "Vị trí hàng đặt nét." },
            { name: "start", type: "int", default: "0", desc: "Cột bắt đầu." },
            { name: "end", type: "none | int", default: "none", desc: "Cột kết thúc." },
            { name: "stroke", type: CELL_STROKE, default: "1pt + black", desc: "Kiểu nét." },
            { name: "position", type: "alignment", default: "top", desc: "Đặt phía trên/dưới hàng." },
          ],
        },
        {
          name: "table.vline", slug: "table.vline", kind: "function",
          signature: "table.vline(x, start, end, stroke, position)",
          summary: "Đường kẻ dọc tuỳ biến.",
          docUrl: `${DOC}table/#definitions-vline`,
          params: [
            { name: "x", type: "auto | int", default: "auto", desc: "Vị trí cột đặt nét." },
            { name: "start", type: "int", default: "0", desc: "Hàng bắt đầu." },
            { name: "end", type: "none | int", default: "none", desc: "Hàng kết thúc." },
            { name: "stroke", type: CELL_STROKE, default: "1pt + black", desc: "Kiểu nét." },
            { name: "position", type: "alignment", default: "start", desc: "Đặt bên trái/phải cột." },
          ],
        },
      ],
    },
    {
      name: "figure",
      slug: "figure",
      kind: "element",
      signature: "figure(body, placement, scope, caption, kind, supplement, numbering, gap, outlined)",
      summary: "Hình/khối minh họa kèm chú thích và đánh số tự động. Kèm figure.caption.",
      docUrl: `${DOC}figure/`,
      snapshotId: "model-figure",
      params: [
        { name: "body", type: "content", positional: true, desc: "Nội dung hình (ảnh, bảng, sơ đồ...)." },
        { name: "placement", type: "none | auto | alignment", default: "none", settable: true, desc: "Cho hình nổi lên đầu/cuối trang." },
        { name: "scope", type: "str", default: '"column"', settable: true, desc: 'Phạm vi nổi: "column" hoặc "parent".' },
        { name: "caption", type: "none | content", default: "none", settable: true, desc: "Chú thích (thường dùng [figure.caption])." },
        { name: "kind", type: "auto | str | function", default: "auto", settable: true, desc: "Loại hình (image/table/raw...) để đánh số riêng." },
        { name: "supplement", type: "none | auto | content | function", default: "auto", settable: true, desc: 'Tiền tố ("Hình"/"Bảng"); auto theo lang.' },
        { name: "numbering", type: "none | str | function", default: '"1"', settable: true, desc: "Kiểu đánh số hình." },
        { name: "gap", type: "length", default: "0.65em", settable: true, desc: "Khoảng cách giữa thân và chú thích." },
        { name: "outlined", type: "bool", default: "true", settable: true, desc: "Có vào danh mục hình/bảng không." },
      ],
      examples: [`#figure(
  image("so-do.png", width: 60%),
  caption: [Sơ đồ tổng quan],
)`],
      paramExamples: [
        { caption: "caption + supplement — chú thích đánh số tự động", snapshotId: "model-figure-caption", width: "320pt", code: `#figure(
  rect(width: 4cm, height: 1.2cm, fill: luma(235)),
  caption: [Sơ đồ khối hệ thống],
)` },
      ],
      members: [
        {
          name: "figure.caption", slug: "figure.caption", kind: "function",
          signature: "figure.caption(position, separator, body)",
          summary: "Chú thích của figure (tuỳ chỉnh vị trí và dấu ngăn).",
          docUrl: `${DOC}figure/#definitions-caption`,
          params: [
            { name: "position", type: "alignment", default: "bottom", settable: true, desc: "Đặt chú thích trên hay dưới hình." },
            { name: "separator", type: "auto | content", default: "auto", settable: true, desc: 'Dấu ngăn giữa nhãn và nội dung (vd ": ").' },
            { name: "body", type: "content", positional: true, desc: "Nội dung chú thích." },
          ],
          paramExamples: [
            { caption: "position — đặt chú thích phía trên", snapshotId: "model-figurecaption-position", width: "320pt", code: `#figure(
  rect(width: 4cm, height: 1.2cm, fill: luma(235)),
  caption: figure.caption(position: top)[Chú thích đặt trên hình],
)` },
          ],
        },
      ],
    },
    {
      name: "outline",
      slug: "outline",
      kind: "element",
      signature: "outline(title, target, depth, indent)",
      summary: "Mục lục — bảng nội dung, danh mục hình/bảng. Kèm outline.entry.",
      docUrl: `${DOC}outline/`,
      snapshotId: "model-outline",
      params: [
        { name: "title", type: "none | auto | content", default: "auto", settable: true, desc: 'Tiêu đề mục lục; auto theo lang ("Mục lục").' },
        { name: "target", type: "label | selector | location", default: "heading", settable: true, desc: "Phần tử cần liệt kê (mặc định là tiêu đề)." },
        { name: "depth", type: "none | int", default: "none", settable: true, desc: "Độ sâu tối đa của cấp tiêu đề." },
        { name: "indent", type: "auto | bool | relative | function", default: "auto", settable: true, desc: "Cách thụt lề theo cấp." },
      ],
      examples: [`#outline(title: "Mục lục", depth: 3)`],
    },
    {
      name: "par",
      slug: "par",
      kind: "element",
      signature: "par(leading, spacing, justify, linebreaks, first-line-indent, hanging-indent, body)",
      summary: "Đoạn văn — điều khiển giãn dòng, căn đều, thụt đầu dòng.",
      docUrl: `${DOC}par/`,
      snapshotId: "model-par",
      params: [
        { name: "leading", type: "length", default: "0.65em", settable: true, desc: "Khoảng cách giữa các dòng trong đoạn." },
        { name: "spacing", type: "length", default: "1.2em", settable: true, desc: "Khoảng cách giữa các đoạn." },
        { name: "justify", type: "bool", default: "false", settable: true, desc: "Căn đều hai bên." },
        { name: "linebreaks", type: "auto | str", default: "auto", settable: true, desc: '"simple" hoặc "optimized" (tối ưu vị trí ngắt).' },
        { name: "first-line-indent", type: "length | dictionary", default: "0pt", settable: true, desc: "Thụt dòng đầu mỗi đoạn." },
        { name: "hanging-indent", type: "length", default: "0pt", settable: true, desc: "Thụt treo các dòng sau dòng đầu." },
        { name: "body", type: "content", positional: true, desc: "Nội dung đoạn." },
      ],
      examples: [`#set par(justify: true, first-line-indent: 1.25em)`],
      paramExamples: [
        { caption: "justify + first-line-indent — căn đều, thụt đầu dòng", snapshotId: "model-par-justify", width: "360pt", code: `#set par(justify: true, first-line-indent: 1.5em)
#lorem(40)` },
      ],
    },
    {
      name: "parbreak",
      slug: "parbreak",
      kind: "function",
      signature: "parbreak()",
      summary: "Ngắt đoạn (tương đương một dòng trống trong markup).",
      docUrl: `${DOC}parbreak/`,
      params: [],
      examples: [`Đoạn một #parbreak() Đoạn hai`],
    },
    {
      name: "strong",
      slug: "strong",
      kind: "function",
      signature: "strong(delta, body)",
      summary: "Nhấn mạnh mạnh (tăng độ đậm). Cú pháp ngắn: *văn bản*.",
      docUrl: `${DOC}strong/`,
      snapshotId: "model-strong",
      params: [
        { name: "delta", type: "int", default: "300", settable: true, desc: "Mức tăng độ đậm font." },
        { name: "body", type: "content", positional: true, desc: "Nội dung in đậm." },
      ],
      examples: [`Đây là *in đậm*.`],
    },
    {
      name: "emph",
      slug: "emph",
      kind: "function",
      signature: "emph(body)",
      summary: "Nhấn mạnh (bật/tắt in nghiêng). Cú pháp ngắn: _văn bản_.",
      docUrl: `${DOC}emph/`,
      snapshotId: "model-emph",
      params: [{ name: "body", type: "content", positional: true, desc: "Nội dung in nghiêng." }],
      examples: [`Đây là _in nghiêng_.`],
    },
    {
      name: "quote",
      slug: "quote",
      kind: "element",
      signature: "quote(block, quotes, attribution, body)",
      summary: "Hiển thị một trích dẫn kèm phần ghi nguồn (attribution) tùy chọn.",
      docUrl: `${DOC}quote/`,
      snapshotId: "model-quote",
      params: [
        { name: "block", type: "bool", default: "false", settable: true, desc: "Hiển thị dạng khối tách riêng (true) hay nội dòng (false)." },
        { name: "quotes", type: "auto | bool", default: "auto", settable: true, desc: "Tự thêm dấu nháy quanh trích dẫn." },
        { name: "attribution", type: "none | content | label", default: "none", settable: true, desc: "Nguồn/tác giả của trích dẫn." },
        { name: "body", type: "content", positional: true, desc: "Nội dung trích dẫn." },
      ],
      examples: [`#quote(block: true, attribution: [Einstein])[
  Trí tưởng tượng quan trọng hơn kiến thức.
]`],
      paramExamples: [
        { caption: "block + attribution — trích dẫn dạng khối có ghi nguồn", snapshotId: "model-quote-attribution", width: "340pt", code: `#quote(block: true, attribution: [— A. Einstein])[
  Trí tưởng tượng quan trọng hơn kiến thức.
]` },
      ],
    },
    {
      name: "link",
      slug: "link",
      kind: "element",
      signature: "link(dest, body)",
      summary: "Liên kết tới URL hoặc một vị trí trong tài liệu.",
      docUrl: `${DOC}link/`,
      snapshotId: "model-link",
      params: [
        { name: "dest", type: "str | label | location | dictionary", positional: true, desc: "Đích đến (URL/nhãn/vị trí)." },
        { name: "body", type: "content", positional: true, desc: "Nội dung hiển thị (mặc định là chính URL)." },
      ],
      examples: [`#link("https://typst.app")[Trang chủ Typst]`],
    },
    {
      name: "ref",
      slug: "ref",
      kind: "element",
      signature: "ref(target, supplement)",
      summary: "Tham chiếu chéo tới một nhãn hoặc nguồn trích dẫn. Cú pháp ngắn: @nhan.",
      docUrl: `${DOC}ref/`,
      snapshotId: "model-ref",
      params: [
        { name: "target", type: "label", positional: true, desc: "Nhãn cần tham chiếu (bắt buộc)." },
        { name: "supplement", type: "auto | none | content | function", default: "auto", settable: true, desc: "Tiền tố hiển thị (vd Hình/Bảng/Mục)." },
      ],
      examples: [`Xem @fig-kientruc và @nguyen2024.`],
    },
    {
      name: "cite",
      slug: "cite",
      kind: "element",
      signature: "cite(key, supplement, form, style)",
      summary: "Trích dẫn một nguồn từ danh mục tham khảo. Cú pháp ngắn: @khoa.",
      docUrl: `${DOC}cite/`,
      params: [
        { name: "key", type: "label", positional: true, desc: "Khoá trích dẫn (bắt buộc)." },
        { name: "supplement", type: "none | content", default: "none", settable: true, desc: "Phần bổ sung (vd số trang)." },
        { name: "form", type: "none | str", default: '"normal"', settable: true, desc: '"normal" | "prose" | "full" | "author" | "year".' },
        { name: "style", type: "auto | str | bytes", default: "auto", settable: true, desc: "Kiểu trích dẫn (theo bibliography nếu auto)." },
      ],
      examples: [`Theo @nguyen2024 thì ...`],
    },
    {
      name: "bibliography",
      slug: "bibliography",
      kind: "element",
      signature: "bibliography(path, title, full, style)",
      summary: "In danh mục tài liệu tham khảo từ file .bib (BibTeX) hoặc .yml (Hayagriva).",
      docUrl: `${DOC}bibliography/`,
      params: [
        { name: "path", type: "str | bytes | array", positional: true, desc: "Đường dẫn file nguồn (bắt buộc); mảng để gộp nhiều file." },
        { name: "title", type: "none | auto | content", default: "auto", settable: true, desc: 'Tiêu đề danh mục; auto theo lang ("Tài liệu tham khảo").' },
        { name: "full", type: "bool", default: "false", settable: true, desc: "Liệt kê cả nguồn không được trích dẫn." },
        { name: "style", type: "str | bytes", default: '"ieee"', settable: true, desc: 'Kiểu trình bày: "ieee", "apa", "chicago-author-date"...' },
      ],
      examples: [`#bibliography("refs.bib", style: "ieee")`],
    },
    {
      name: "footnote",
      slug: "footnote",
      kind: "element",
      signature: "footnote(numbering, body)",
      summary: "Chú thích chân trang. Kèm footnote.entry để tùy biến phần liệt kê.",
      docUrl: `${DOC}footnote/`,
      snapshotId: "model-footnote",
      params: [
        { name: "numbering", type: "str | function", default: '"1"', settable: true, desc: "Kiểu đánh số chú thích." },
        { name: "body", type: "content | label", positional: true, desc: "Nội dung chú thích (hoặc nhãn tới chú thích đã có)." },
      ],
      examples: [`Một khẳng định#footnote[Nguồn: ...].`],
    },
    {
      name: "numbering",
      slug: "numbering",
      kind: "function",
      signature: "numbering(numbering, ..numbers)",
      summary: "Áp dụng một định dạng đánh số cho dãy số cho trước.",
      docUrl: `${DOC}numbering/`,
      snapshotId: "model-numbering",
      params: [
        { name: "numbering", type: "str | function", positional: true, desc: 'Mẫu đánh số, vd "1.1", "A.", "i".' },
        { name: "numbers", type: "int", positional: true, desc: "Các số cần định dạng (biến thiên ..)." },
      ],
      examples: [`#numbering("1.1", 1, 2)  // → 1.2`],
    },
    {
      name: "document",
      slug: "document",
      kind: "element",
      signature: "document(title, author, keywords, date)",
      summary: "Quản lý metadata tài liệu (đặt qua set rule, ảnh hưởng thuộc tính PDF).",
      docUrl: `${DOC}document/`,
      params: [
        { name: "title", type: "none | auto | content", default: "auto", settable: true, desc: "Tiêu đề tài liệu." },
        { name: "author", type: "str | array", default: "()", settable: true, desc: "Tác giả (một hoặc nhiều)." },
        { name: "keywords", type: "str | array", default: "()", settable: true, desc: "Từ khoá." },
        { name: "date", type: "none | auto | datetime", default: "auto", settable: true, desc: "Ngày tạo tài liệu." },
      ],
      examples: [`#set document(title: "Đồ án", author: "Nguyễn Văn A")`],
    },
  ],
};
