import { Type } from "lucide-react";
import type { ReferenceCategory } from "./types";

const DOC = "https://typst.app/docs/reference/text/";
const DECO_STROKE = "auto | none | length | color | gradient | stroke | dictionary";

export const text: ReferenceCategory = {
  slug: "text",
  title: "Văn bản (Text)",
  icon: Type,
  summary: "Định dạng chữ (font, cỡ, màu, ngôn ngữ), trang trí (gạch chân/ngang, tô nền), chỉ số trên/dưới, chữ hoa nhỏ, mã thô.",
  docUrl: DOC,
  fns: [
    {
      name: "text",
      slug: "text",
      kind: "function",
      signature: "text(font, size, fill, weight, style, stretch, tracking, spacing, lang, region, dir, hyphenate, fallback, body)",
      summary: "Tùy chỉnh toàn bộ thuộc tính chữ; dùng qua #set text(...) cho toàn cục hoặc #text(...)[...] cho một đoạn.",
      docUrl: `${DOC}text/`,
      snapshotId: "text-text",
      params: [
        { name: "font", type: "str | array | dictionary", default: '"libertinus serif"', settable: true, desc: "Font hoặc danh sách ưu tiên." },
        { name: "size", type: "length", default: "11pt", settable: true, desc: "Cỡ chữ (cơ sở cho đơn vị em)." },
        { name: "fill", type: "color | gradient | tiling", default: "đen", settable: true, desc: "Màu chữ." },
        { name: "weight", type: "int | str", default: '"regular"', settable: true, desc: 'Độ đậm 100–900 hoặc "bold".' },
        { name: "style", type: "str", default: '"normal"', settable: true, desc: '"normal" | "italic" | "oblique".' },
        { name: "stretch", type: "ratio", default: "100%", settable: true, desc: "Co giãn bề ngang glyph." },
        { name: "tracking", type: "length", default: "0pt", settable: true, desc: "Khoảng cách giữa các ký tự." },
        { name: "spacing", type: "relative", default: "100%", settable: true, desc: "Khoảng cách giữa các từ." },
        { name: "lang", type: "str", default: '"en"', settable: true, desc: "Mã ngôn ngữ (ngắt từ, nháy thông minh)." },
        { name: "region", type: "none | str", default: "none", settable: true, desc: "Mã vùng (ISO 3166, vd VN)." },
        { name: "dir", type: "auto | direction", default: "auto", settable: true, desc: "Hướng chữ: ltr | rtl." },
        { name: "hyphenate", type: "auto | bool", default: "auto", settable: true, desc: "Bật/tắt ngắt từ khi xuống dòng." },
        { name: "fallback", type: "bool", default: "true", settable: true, desc: "Dự phòng font khi thiếu glyph." },
        { name: "stroke", type: "none | length | color | gradient | stroke | dictionary", default: "none", settable: true, desc: "Viền nét chữ." },
        { name: "baseline", type: "length", default: "0pt", settable: true, desc: "Dời đường cơ sở (nâng/hạ chữ)." },
        { name: "script", type: "auto | str", default: "auto", settable: true, desc: 'Hệ chữ viết OpenType (vd "latn").' },
        { name: "cjk-latin-spacing", type: "none | auto", default: "auto", settable: true, desc: "Tự thêm khoảng cách giữa chữ CJK và Latin." },
        { name: "kerning", type: "bool", default: "true", settable: true, desc: "Kerning (canh khoảng cặp ký tự)." },
        { name: "ligatures", type: "bool", default: "true", settable: true, desc: 'Ligature chuẩn (vd "fi").' },
        { name: "discretionary-ligatures", type: "bool", default: "false", settable: true, desc: "Ligature tuỳ chọn (ít dùng)." },
        { name: "number-type", type: "auto | str", default: "auto", settable: true, desc: '"lining" (số thẳng) hoặc "old-style" (số cổ).' },
        { name: "number-width", type: "auto | str", default: "auto", settable: true, desc: '"proportional" hoặc "tabular" (số đều cột).' },
        { name: "slashed-zero", type: "bool", default: "false", settable: true, desc: "Số 0 có gạch chéo." },
        { name: "fractions", type: "bool", default: "false", settable: true, desc: "Tự dựng phân số (vd 1/2)." },
        { name: "stylistic-set", type: "none | int | array", default: "()", settable: true, desc: "Bộ biến thể OpenType (ss01–ss20)." },
        { name: "features", type: "array | dictionary", default: "(:)", settable: true, desc: "Tính năng OpenType thô." },
        { name: "top-edge / bottom-edge", type: "length | str", default: '"cap-height" / "baseline"', settable: true, desc: "Biên trên/dưới khung chữ." },
        { name: "body", type: "content", positional: true, desc: "Nội dung áp dụng định dạng." },
      ],
      examples: [`#set text(font: "Times New Roman", size: 13pt, lang: "vi")
#text(weight: "bold")[Đậm], #text(fill: blue)[xanh],
#text(tracking: 1.5pt)[giãn].`],
      paramExamples: [
        { caption: "weight — độ đậm", snapshotId: "text-text-weight", code: `#text(weight: "bold")[Đậm] · #text(weight: "light")[mảnh] · thường` },
        { caption: "style — nghiêng", snapshotId: "text-text-style", code: `#text(style: "italic")[Chữ nghiêng] · chữ đứng` },
        { caption: "size — cỡ chữ", snapshotId: "text-text-size", code: `#text(size: 20pt)[To] · #text(size: 10pt)[nhỏ]` },
        { caption: "fill — màu chữ", snapshotId: "text-text-fill", code: `#text(fill: blue)[Xanh] · #text(fill: red)[đỏ] · #text(fill: green)[lục]` },
        { caption: "tracking — giãn ký tự", snapshotId: "text-text-tracking", code: `#text(tracking: 3pt)[GIÃN] · bình thường` },
      ],
    },
    {
      name: "linebreak",
      slug: "linebreak",
      kind: "function",
      signature: "linebreak(justify)",
      summary: "Chèn một dấu ngắt dòng (tương đương dấu \\ trong markup).",
      docUrl: `${DOC}linebreak/`,
      snapshotId: "text-linebreak",
      params: [
        { name: "justify", type: "bool", default: "false", settable: true, desc: "Căn đều dòng trước khi ngắt." },
      ],
      examples: [`Dòng một #linebreak() Dòng hai`],
    },
    {
      name: "smartquote",
      slug: "smartquote",
      kind: "function",
      signature: "smartquote(double, enabled, alternative, quotes)",
      summary: "Dấu nháy thông minh, tự đổi kiểu theo ngôn ngữ và ngữ cảnh.",
      docUrl: `${DOC}smartquote/`,
      params: [
        { name: "double", type: "bool", default: "true", settable: true, desc: "Nháy đôi (true) hay nháy đơn (false)." },
        { name: "enabled", type: "bool", default: "true", settable: true, desc: "Bật/tắt chuyển nháy thông minh." },
        { name: "alternative", type: "bool", default: "false", settable: true, desc: "Dùng biến thể thay thế của nháy." },
        { name: "quotes", type: "auto | str | array | dictionary", default: "auto", settable: true, desc: "Bộ nháy tùy chỉnh." },
      ],
      examples: [`#set smartquote(enabled: false)  // giữ nháy thẳng`],
    },
    {
      name: "sub",
      slug: "sub",
      kind: "function",
      signature: "sub(typographic, baseline, size, body)",
      summary: "Hiển thị văn bản dạng chỉ số dưới (subscript).",
      docUrl: `${DOC}sub/`,
      snapshotId: "text-sub",
      params: [
        { name: "typographic", type: "bool", default: "true", settable: true, desc: "Dùng glyph chỉ số dưới sẵn có của font nếu được." },
        { name: "baseline", type: "length", default: "0.2em", settable: true, desc: "Độ dời đường cơ sở khi không dùng glyph sẵn." },
        { name: "size", type: "length", default: "0.6em", settable: true, desc: "Cỡ chữ khi không dùng glyph sẵn." },
        { name: "body", type: "content", positional: true, desc: "Nội dung làm chỉ số dưới." },
      ],
      examples: [`H#sub[2]O`],
    },
    {
      name: "super",
      slug: "super",
      kind: "function",
      signature: "super(typographic, baseline, size, body)",
      summary: "Hiển thị văn bản dạng chỉ số trên (superscript).",
      docUrl: `${DOC}super/`,
      snapshotId: "text-super",
      params: [
        { name: "typographic", type: "bool", default: "true", settable: true, desc: "Dùng glyph chỉ số trên sẵn có của font nếu được." },
        { name: "baseline", type: "length", default: "-0.5em", settable: true, desc: "Độ dời đường cơ sở khi không dùng glyph sẵn." },
        { name: "size", type: "length", default: "0.6em", settable: true, desc: "Cỡ chữ khi không dùng glyph sẵn." },
        { name: "body", type: "content", positional: true, desc: "Nội dung làm chỉ số trên." },
      ],
      examples: [`x#super[2] + 1`],
    },
    {
      name: "underline",
      slug: "underline",
      kind: "function",
      signature: "underline(stroke, offset, extent, evade, background, body)",
      summary: "Gạch chân (đường kẻ bên dưới) văn bản.",
      docUrl: `${DOC}underline/`,
      snapshotId: "text-underline",
      params: [
        { name: "stroke", type: DECO_STROKE, default: "auto", settable: true, desc: "Kiểu nét gạch." },
        { name: "offset", type: "auto | length", default: "auto", settable: true, desc: "Khoảng cách từ đường cơ sở tới nét gạch." },
        { name: "extent", type: "length", default: "0pt", settable: true, desc: "Nới dài nét gạch về hai phía." },
        { name: "evade", type: "bool", default: "true", settable: true, desc: "Tránh nét gạch cắt qua phần chữ thò xuống." },
        { name: "background", type: "bool", default: "false", settable: true, desc: "Vẽ nét phía sau chữ." },
        { name: "body", type: "content", positional: true, desc: "Nội dung gạch chân." },
      ],
      examples: [`#underline[Văn bản gạch chân]`],
      paramExamples: [
        { caption: "stroke — kiểu nét gạch", snapshotId: "text-underline-stroke", code: `#underline(stroke: 1.5pt + red)[Gạch chân đỏ dày]` },
        { caption: "offset — hạ nét xuống", snapshotId: "text-underline-offset", code: `#underline(offset: 4pt)[Nét gạch cách xa chữ]` },
      ],
    },
    {
      name: "overline",
      slug: "overline",
      kind: "function",
      signature: "overline(stroke, offset, extent, evade, background, body)",
      summary: "Thêm một đường kẻ phía trên văn bản.",
      docUrl: `${DOC}overline/`,
      snapshotId: "text-overline",
      params: [
        { name: "stroke", type: DECO_STROKE, default: "auto", settable: true, desc: "Kiểu nét kẻ." },
        { name: "offset", type: "auto | length", default: "auto", settable: true, desc: "Khoảng cách tới nét kẻ trên." },
        { name: "extent", type: "length", default: "0pt", settable: true, desc: "Nới dài nét về hai phía." },
        { name: "evade", type: "bool", default: "true", settable: true, desc: "Tránh cắt qua phần chữ thò lên." },
        { name: "background", type: "bool", default: "false", settable: true, desc: "Vẽ nét phía sau chữ." },
        { name: "body", type: "content", positional: true, desc: "Nội dung kẻ trên." },
      ],
      examples: [`#overline[Văn bản kẻ trên]`],
    },
    {
      name: "strike",
      slug: "strike",
      kind: "function",
      signature: "strike(stroke, offset, extent, background, body)",
      summary: "Gạch ngang (kẻ xuyên qua) văn bản.",
      docUrl: `${DOC}strike/`,
      snapshotId: "text-strike",
      params: [
        { name: "stroke", type: DECO_STROKE, default: "auto", settable: true, desc: "Kiểu nét gạch ngang." },
        { name: "offset", type: "auto | length", default: "auto", settable: true, desc: "Vị trí nét so với đường giữa chữ." },
        { name: "extent", type: "length", default: "0pt", settable: true, desc: "Nới dài nét về hai phía." },
        { name: "background", type: "bool", default: "false", settable: true, desc: "Vẽ nét phía sau chữ." },
        { name: "body", type: "content", positional: true, desc: "Nội dung gạch ngang." },
      ],
      examples: [`#strike[Văn bản bị gạch]`],
      paramExamples: [
        { caption: "stroke — nét gạch ngang", snapshotId: "text-strike-stroke", code: `#strike(stroke: 2pt + red)[Đoạn bị gạch ngang đỏ]` },
      ],
    },
    {
      name: "highlight",
      slug: "highlight",
      kind: "function",
      signature: "highlight(fill, stroke, top-edge, bottom-edge, extent, radius, body)",
      summary: "Tô nền (đánh dấu) cho văn bản bằng một màu nền.",
      docUrl: `${DOC}highlight/`,
      snapshotId: "text-highlight",
      params: [
        { name: "fill", type: "none | color | gradient | tiling", default: "vàng nhạt", settable: true, desc: "Màu nền tô." },
        { name: "stroke", type: "none | length | color | gradient | stroke | dictionary", default: "none", settable: true, desc: "Viền quanh vùng tô." },
        { name: "top-edge", type: "length | str", default: '"ascender"', settable: true, desc: "Cạnh trên vùng tô." },
        { name: "bottom-edge", type: "length | str", default: '"descender"', settable: true, desc: "Cạnh dưới vùng tô." },
        { name: "extent", type: "length", default: "0pt", settable: true, desc: "Nới rộng vùng tô về hai phía." },
        { name: "radius", type: "relative | dictionary", default: "(:)", settable: true, desc: "Bo góc vùng tô." },
        { name: "body", type: "content", positional: true, desc: "Nội dung được tô nền." },
      ],
      examples: [`#highlight[Đoạn được tô nền]`],
      paramExamples: [
        { caption: "fill — màu nền tô", snapshotId: "text-highlight-fill", code: `#highlight(fill: aqua)[tô lam] và #highlight(fill: yellow)[tô vàng]` },
        { caption: "radius — bo góc vùng tô", snapshotId: "text-highlight-radius", code: `#highlight(fill: yellow, radius: 4pt)[Vùng tô bo góc]` },
      ],
    },
    {
      name: "raw",
      slug: "raw",
      kind: "function",
      signature: "raw(text, block, lang, align, syntaxes, theme, tab-size)",
      summary: "Văn bản thô (mã nguồn) có tùy chọn tô màu cú pháp; tương đương `...` và ```...```.",
      docUrl: `${DOC}raw/`,
      snapshotId: "text-raw",
      params: [
        { name: "text", type: "str", positional: true, desc: "Mã nguồn thô (bắt buộc)." },
        { name: "block", type: "bool", default: "false", settable: true, desc: "Hiển thị dạng khối nhiều dòng (true) hay nội dòng (false)." },
        { name: "lang", type: "none | str", default: "none", settable: true, desc: "Ngôn ngữ để tô màu cú pháp." },
        { name: "align", type: "alignment", default: "start", settable: true, desc: "Căn lề trong khối mã." },
        { name: "syntaxes", type: "str | array", default: "()", settable: true, desc: "File định nghĩa cú pháp bổ sung (.sublime-syntax)." },
        { name: "theme", type: "none | auto | str", default: "auto", settable: true, desc: "Chủ đề tô màu (.tmTheme)." },
        { name: "tab-size", type: "int", default: "2", settable: true, desc: "Số khoảng trắng cho một tab." },
      ],
      examples: ['#raw("let x = 1", lang: "rust", block: true)'],
      members: [
        {
          name: "raw.line", slug: "raw.line", kind: "function",
          signature: "raw.line(number, count, text, body)",
          summary: "Một dòng trong khối raw (dùng khi tuỳ biến hiển thị qua show rule).",
          docUrl: `${DOC}raw/#definitions-line`,
          params: [
            { name: "number", type: "int", positional: true, desc: "Số thứ tự dòng (bắt đầu từ 1)." },
            { name: "count", type: "int", positional: true, desc: "Tổng số dòng của khối." },
            { name: "text", type: "str", positional: true, desc: "Nội dung dòng dạng chuỗi." },
            { name: "body", type: "content", positional: true, desc: "Nội dung dòng đã tô màu." },
          ],
        },
      ],
    },
    {
      name: "smallcaps",
      slug: "smallcaps",
      kind: "function",
      signature: "smallcaps(all, body)",
      summary: "Hiển thị văn bản dạng chữ hoa nhỏ (small capitals).",
      docUrl: `${DOC}smallcaps/`,
      snapshotId: "text-smallcaps",
      params: [
        { name: "all", type: "bool", default: "false", settable: true, desc: "Áp dụng cho cả chữ hoa (all-small-caps) chứ không chỉ chữ thường." },
        { name: "body", type: "content", positional: true, desc: "Nội dung chuyển chữ hoa nhỏ." },
      ],
      examples: [`#smallcaps[Tiêu đề chữ hoa nhỏ]`],
      paramExamples: [
        { caption: "all — áp dụng cả chữ hoa", snapshotId: "text-smallcaps-all", code: `#smallcaps(all: true)[Tiêu Đề ABC] · #smallcaps[Tiêu Đề ABC]` },
      ],
    },
    {
      name: "upper",
      slug: "upper",
      kind: "function",
      signature: "upper(text)",
      summary: "Chuyển chuỗi/nội dung sang chữ HOA.",
      docUrl: `${DOC}upper/`,
      snapshotId: "text-upper",
      params: [{ name: "text", type: "str | content", positional: true, desc: "Chuỗi hoặc nội dung cần chuyển." }],
      examples: [`#upper[viết hoa] → VIẾT HOA`],
    },
    {
      name: "lower",
      slug: "lower",
      kind: "function",
      signature: "lower(text)",
      summary: "Chuyển chuỗi/nội dung sang chữ thường.",
      docUrl: `${DOC}lower/`,
      snapshotId: "text-lower",
      params: [{ name: "text", type: "str | content", positional: true, desc: "Chuỗi hoặc nội dung cần chuyển." }],
      examples: [`#lower[VIẾT THƯỜNG] → viết thường`],
    },
    {
      name: "lorem",
      slug: "lorem",
      kind: "function",
      signature: "lorem(words)",
      summary: "Tạo văn bản giả (Lorem ipsum) để thử bố cục.",
      docUrl: `${DOC}lorem/`,
      snapshotId: "text-lorem",
      params: [{ name: "words", type: "int", positional: true, desc: "Số từ cần tạo." }],
      examples: [`#lorem(20)`],
    },
  ],
};
