import { Shapes } from "lucide-react";
import type { ReferenceCategory } from "./types";

const DOC = "https://typst.app/docs/reference/visualize/";

/** Kiểu nét dùng lại cho fill/stroke ở nhiều hình. */
const FILL = "none | color | gradient | tiling";
const STROKE = "none | auto | length | color | gradient | stroke | tiling | dictionary";

export const visualize: ReferenceCategory = {
  slug: "visualize",
  title: "Trực quan (Visualize)",
  icon: Shapes,
  summary: "Chèn ảnh, vẽ hình cơ bản (đường, hình chữ nhật, tròn, đa giác, đường cong) và các kiểu nét/màu/chuyển sắc/họa tiết.",
  docUrl: DOC,
  fns: [
    {
      name: "image",
      slug: "image",
      kind: "element",
      signature: "image(source, format, width, height, alt, page, fit, scaling, icc)",
      summary: "Chèn ảnh raster hoặc đồ họa vector (PNG, JPG, GIF, SVG, PDF, WEBP).",
      docUrl: `${DOC}image/`,
      params: [
        { name: "source", type: "str | path | bytes", positional: true, desc: "Đường dẫn file ảnh hoặc dữ liệu ảnh thô (bắt buộc)." },
        { name: "format", type: "auto | str | dictionary", default: "auto", settable: true, desc: 'Định dạng ảnh (png, jpg, gif, svg, pdf, webp) hoặc đặc tả pixel thô.' },
        { name: "width", type: "auto | relative", default: "auto", settable: true, desc: "Chiều rộng ảnh." },
        { name: "height", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều cao ảnh." },
        { name: "alt", type: "none | str", default: "none", settable: true, desc: "Văn bản mô tả cho trợ năng (screen reader)." },
        { name: "page", type: "int", default: "1", settable: true, desc: "Số trang cần nhúng (chỉ áp dụng cho file PDF)." },
        { name: "fit", type: "str", default: '"cover"', settable: true, desc: 'Cách co ảnh: "cover", "contain", "stretch".' },
        { name: "scaling", type: "auto | str", default: "auto", settable: true, desc: 'Gợi ý dựng ảnh: "smooth" hoặc "pixelated".' },
        { name: "icc", type: "auto | str | path | bytes", default: "auto", settable: true, desc: "Hồ sơ màu ICC để hiển thị màu chính xác." },
      ],
      examples: [`#figure(
  image("hinh/so-do.png", width: 80%, alt: "Sơ đồ pipeline"),
  caption: [Một pipeline xử lý],
)`],
    },
    {
      name: "line",
      slug: "line",
      kind: "element",
      signature: "line(start, end, length, angle, stroke)",
      summary: "Vẽ một đoạn thẳng từ điểm này tới điểm khác (hoặc theo độ dài + góc).",
      docUrl: `${DOC}line/`,
      snapshotId: "visualize-line",
      params: [
        { name: "start", type: "array", default: "(0pt, 0pt)", settable: true, positional: true, desc: "Điểm bắt đầu — mảng gồm đúng hai relative length." },
        { name: "end", type: "none | array", default: "none", settable: true, positional: true, desc: "Điểm kết thúc của đoạn thẳng." },
        { name: "length", type: "relative", default: "0% + 30pt", settable: true, positional: true, desc: "Độ dài đoạn (chỉ dùng khi end là none)." },
        { name: "angle", type: "angle", default: "0deg", settable: true, positional: true, desc: "Góc nghiêng so với gốc (chỉ dùng khi end là none)." },
        { name: "stroke", type: "length | color | gradient | stroke | tiling | dictionary", default: "1pt + black", settable: true, positional: true, desc: "Kiểu nét vẽ." },
      ],
      examples: [`#line(length: 100%)
#line(end: (50%, 50%))
#line(length: 4cm, stroke: 2pt + maroon)`],
      paramExamples: [
        { caption: "length + angle — đoạn nghiêng", snapshotId: "visualize-line-angle", code: `#line(length: 3.5cm, angle: 30deg, stroke: 1.5pt)` },
        { caption: "stroke — màu & độ dày", snapshotId: "visualize-line-stroke", code: `#line(length: 4cm, stroke: 3pt + maroon)` },
      ],
    },
    {
      name: "rect",
      slug: "rect",
      kind: "element",
      signature: "rect(width, height, fill, stroke, radius, inset, outset, body)",
      summary: "Vẽ hình chữ nhật, có thể chứa nội dung bên trong.",
      docUrl: `${DOC}rect/`,
      snapshotId: "visualize-rect",
      params: [
        { name: "width", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều rộng; auto thì co theo nội dung." },
        { name: "height", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều cao; auto thì co theo nội dung." },
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu/họa tiết tô bên trong." },
        { name: "stroke", type: STROKE, default: "auto", settable: true, desc: "Nét viền; có thể đặt riêng từng cạnh qua dictionary." },
        { name: "radius", type: "relative | dictionary", default: "(:)", settable: true, desc: "Bo góc; dictionary để bo riêng từng góc." },
        { name: "inset", type: "relative | dictionary", default: "0% + 5pt", settable: true, desc: "Đệm trong quanh nội dung." },
        { name: "outset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Nới ngoài (không ảnh hưởng bố cục)." },
        { name: "body", type: "none | content", default: "none", settable: true, positional: true, desc: "Nội dung bên trong; hình co theo nếu không đặt kích thước." },
      ],
      examples: [`#rect(width: 4cm, height: 1.6cm, radius: 4pt,
     fill: blue.lighten(85%), stroke: blue)[Hộp]`],
      paramExamples: [
        { caption: "radius — bo góc", snapshotId: "visualize-rect-radius", code: `#rect(width: 3cm, height: 1.3cm, radius: 10pt, stroke: blue)` },
        { caption: "stroke — nét đứt", snapshotId: "visualize-rect-stroke-dashed", code: `#rect(width: 3cm, height: 1.3cm, stroke: (paint: blue, thickness: 1.5pt, dash: "dashed"))` },
        { caption: "fill — chuyển sắc", snapshotId: "visualize-rect-fill-gradient", code: `#rect(width: 3cm, height: 1.3cm, fill: gradient.linear(blue, purple))` },
        { caption: "inset — đệm trong quanh nội dung", snapshotId: "visualize-rect-inset", code: `#rect(inset: 12pt, stroke: blue)[Nội dung có đệm rộng]` },
      ],
    },
    {
      name: "square",
      slug: "square",
      kind: "element",
      signature: "square(size, width, height, fill, stroke, radius, inset, outset, body)",
      summary: "Vẽ hình vuông (cạnh bằng nhau), có thể chứa nội dung.",
      docUrl: `${DOC}square/`,
      snapshotId: "visualize-square",
      params: [
        { name: "size", type: "auto | length", default: "auto", settable: true, desc: "Cạnh hình vuông; loại trừ lẫn nhau với width/height." },
        { name: "width", type: "auto | relative", default: "auto", settable: true, desc: "Chiều rộng (loại trừ size)." },
        { name: "height", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều cao (loại trừ size)." },
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu/họa tiết tô bên trong." },
        { name: "stroke", type: STROKE, default: "auto", settable: true, desc: "Nét viền." },
        { name: "radius", type: "relative | dictionary", default: "(:)", settable: true, desc: "Bo góc." },
        { name: "inset", type: "relative | dictionary", default: "0% + 5pt", settable: true, desc: "Đệm trong." },
        { name: "outset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Nới ngoài." },
        { name: "body", type: "none | content", default: "none", settable: true, positional: true, desc: "Nội dung bên trong." },
      ],
      examples: [`#square(size: 2cm, fill: green.lighten(80%), stroke: green)`],
      paramExamples: [
        { caption: "radius — bo góc", snapshotId: "visualize-square-radius", code: `#square(size: 2cm, radius: 8pt, fill: green.lighten(80%), stroke: green)` },
        { caption: "fill — chuyển sắc", snapshotId: "visualize-square-fill", code: `#square(size: 2cm, fill: gradient.linear(green, blue))` },
      ],
    },
    {
      name: "ellipse",
      slug: "ellipse",
      kind: "element",
      signature: "ellipse(width, height, fill, stroke, inset, outset, body)",
      summary: "Vẽ hình elip, có thể chứa nội dung.",
      docUrl: `${DOC}ellipse/`,
      snapshotId: "visualize-ellipse",
      params: [
        { name: "width", type: "auto | relative", default: "auto", settable: true, desc: "Chiều rộng." },
        { name: "height", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều cao." },
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu/họa tiết tô bên trong." },
        { name: "stroke", type: STROKE, default: "auto", settable: true, desc: "Nét viền." },
        { name: "inset", type: "relative | dictionary", default: "0% + 5pt", settable: true, desc: "Đệm trong." },
        { name: "outset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Nới ngoài." },
        { name: "body", type: "none | content", default: "none", settable: true, positional: true, desc: "Nội dung bên trong." },
      ],
      examples: [`#ellipse(width: 4cm, height: 2cm, fill: orange.lighten(80%))`],
      paramExamples: [
        { caption: "width/height — tỉ lệ bầu dục", snapshotId: "visualize-ellipse-size", code: `#ellipse(width: 4cm, height: 1.6cm, fill: orange.lighten(80%), stroke: orange)` },
      ],
    },
    {
      name: "circle",
      slug: "circle",
      kind: "element",
      signature: "circle(radius, width, height, fill, stroke, inset, outset, body)",
      summary: "Vẽ hình tròn, có thể chứa nội dung (giữ tỉ lệ 1:1).",
      docUrl: `${DOC}circle/`,
      snapshotId: "visualize-circle",
      params: [
        { name: "radius", type: "length", default: "0pt", desc: "Bán kính; loại trừ lẫn nhau với width và height." },
        { name: "width", type: "auto | relative", default: "auto", settable: true, desc: "Chiều rộng; loại trừ radius và height." },
        { name: "height", type: "auto | relative | fraction", default: "auto", settable: true, desc: "Chiều cao; loại trừ radius và width." },
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu/họa tiết tô bên trong." },
        { name: "stroke", type: STROKE, default: "auto", settable: true, desc: "Nét viền." },
        { name: "inset", type: "relative | dictionary", default: "0% + 5pt", settable: true, desc: "Đệm trong quanh nội dung." },
        { name: "outset", type: "relative | dictionary", default: "(:)", settable: true, desc: "Nới ngoài (không ảnh hưởng bố cục)." },
        { name: "body", type: "none | content", default: "none", settable: true, positional: true, desc: "Nội dung bên trong; hình co theo, giữ tỉ lệ 1:1." },
      ],
      examples: [`#circle(radius: 25pt)`, `#circle[
  #set align(center + horizon)
  Vừa khít nội dung.
]`],
      paramExamples: [
        { caption: "fill — màu tô", snapshotId: "visualize-circle-fill", code: `#circle(radius: 22pt, fill: blue.lighten(60%))` },
        { caption: "stroke — viền dày", snapshotId: "visualize-circle-stroke", code: `#circle(radius: 22pt, stroke: 2pt + maroon)` },
        { caption: "radius vs width/height (loại trừ nhau)", snapshotId: "visualize-circle-radius", code: `#circle(radius: 18pt, fill: green.lighten(70%))` },
      ],
    },
    {
      name: "polygon",
      slug: "polygon",
      kind: "element",
      signature: "polygon(fill, fill-rule, stroke, ..vertices)",
      summary: "Vẽ đa giác khép kín từ danh sách đỉnh. Có biến thể polygon.regular cho đa giác đều.",
      docUrl: `${DOC}polygon/`,
      snapshotId: "visualize-polygon",
      params: [
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu/họa tiết tô bên trong." },
        { name: "fill-rule", type: "str", default: '"non-zero"', settable: true, desc: 'Quy tắc tô: "non-zero" hoặc "even-odd".' },
        { name: "stroke", type: STROKE, default: "auto", settable: true, desc: "Nét viền (auto = 1pt đen khi không có fill)." },
        { name: "vertices", type: "array", positional: true, desc: "Các đỉnh — mỗi đỉnh là mảng hai relative length (biến thiên ..)." },
      ],
      examples: [`#polygon.regular(
  fill: blue.lighten(80%), stroke: blue,
  size: 30pt, vertices: 5,
)`],
      paramExamples: [
        { caption: "vertices — 3 / 5 / 6 đỉnh", snapshotId: "visualize-polygon-vertices", code: `#stack(dir: ltr, spacing: 10pt,
  polygon.regular(fill: blue.lighten(80%), vertices: 3, size: 22pt),
  polygon.regular(fill: blue.lighten(80%), vertices: 5, size: 22pt),
  polygon.regular(fill: blue.lighten(80%), vertices: 6, size: 22pt),
)` },
      ],
      members: [
        {
          name: "polygon.regular", slug: "polygon.regular", kind: "function",
          signature: "polygon.regular(fill, stroke, size, vertices)",
          summary: "Đa giác đều (tam giác, ngũ giác...).",
          docUrl: `${DOC}polygon/#definitions-regular`,
          params: [
            { name: "fill", type: FILL, default: "none", desc: "Màu/họa tiết tô." },
            { name: "stroke", type: STROKE, default: "auto", desc: "Nét viền." },
            { name: "size", type: "length", default: "1em", desc: "Đường kính đường tròn ngoại tiếp." },
            { name: "vertices", type: "int", default: "3", desc: "Số đỉnh (số cạnh)." },
          ],
        },
      ],
    },
    {
      name: "curve",
      slug: "curve",
      kind: "element",
      signature: "curve(fill, fill-rule, stroke, ..components)",
      summary: "Vẽ đường cong gồm các lệnh di chuyển/đoạn thẳng/Bézier (curve.move, curve.line, curve.quad, curve.cubic, curve.close).",
      docUrl: `${DOC}curve/`,
      snapshotId: "visualize-curve",
      versionNote: "Thay cho phần tử `path` (đã bị bỏ từ Typst v0.13).",
      params: [
        { name: "fill", type: FILL, default: "none", settable: true, desc: "Màu/họa tiết tô bên trong." },
        { name: "fill-rule", type: "str", default: '"non-zero"', settable: true, desc: 'Quy tắc tô: "non-zero" hoặc "even-odd".' },
        { name: "stroke", type: STROKE, default: "auto", settable: true, desc: "Nét viền." },
        { name: "components", type: "content", positional: true, desc: "Các thành phần dựng đường cong (move/line/quad/cubic/close), biến thiên .." },
      ],
      examples: [`#curve(
  fill: blue.lighten(80%), stroke: blue,
  curve.move((0pt, 50pt)),
  curve.line((100pt, 50pt)),
  curve.cubic(none, (90pt, 0pt), (50pt, 0pt)),
  curve.close(),
)`],
      members: [
        {
          name: "curve.move", slug: "curve.move", kind: "function",
          signature: "curve.move(start, relative)",
          summary: "Dời con trỏ tới điểm mới mà không vẽ.",
          docUrl: `${DOC}curve/#definitions-move`,
          params: [
            { name: "start", type: "array", positional: true, desc: "Điểm đích (x, y)." },
            { name: "relative", type: "bool", default: "false", desc: "Toạ độ tương đối so với điểm trước." },
          ],
        },
        {
          name: "curve.line", slug: "curve.line", kind: "function",
          signature: "curve.line(end, relative)",
          summary: "Vẽ đoạn thẳng tới điểm.",
          docUrl: `${DOC}curve/#definitions-line`,
          params: [
            { name: "end", type: "array", positional: true, desc: "Điểm kết thúc." },
            { name: "relative", type: "bool", default: "false", desc: "Toạ độ tương đối." },
          ],
        },
        {
          name: "curve.quad", slug: "curve.quad", kind: "function",
          signature: "curve.quad(control, end, relative)",
          summary: "Đoạn Bézier bậc hai (một điểm điều khiển).",
          docUrl: `${DOC}curve/#definitions-quad`,
          params: [
            { name: "control", type: "none | auto | array", positional: true, desc: "Điểm điều khiển (auto = phản chiếu điểm trước)." },
            { name: "end", type: "array", positional: true, desc: "Điểm kết thúc." },
            { name: "relative", type: "bool", default: "false", desc: "Toạ độ tương đối." },
          ],
        },
        {
          name: "curve.cubic", slug: "curve.cubic", kind: "function",
          signature: "curve.cubic(control-start, control-end, end, relative)",
          summary: "Đoạn Bézier bậc ba (hai điểm điều khiển).",
          docUrl: `${DOC}curve/#definitions-cubic`,
          params: [
            { name: "control-start", type: "none | auto | array", positional: true, desc: "Điểm điều khiển đầu." },
            { name: "control-end", type: "none | array", positional: true, desc: "Điểm điều khiển cuối." },
            { name: "end", type: "array", positional: true, desc: "Điểm kết thúc." },
            { name: "relative", type: "bool", default: "false", desc: "Toạ độ tương đối." },
          ],
        },
        {
          name: "curve.close", slug: "curve.close", kind: "function",
          signature: "curve.close(mode)",
          summary: "Khép đường cong về điểm bắt đầu.",
          docUrl: `${DOC}curve/#definitions-close`,
          params: [{ name: "mode", type: "str", default: '"smooth"', desc: '"smooth" (theo điểm điều khiển) hoặc "straight".' }],
        },
      ],
    },
    {
      name: "stroke",
      slug: "stroke",
      kind: "type",
      signature: "stroke(paint, thickness, cap, join, dash, miter-limit)",
      summary: "Kiểu dữ liệu định nghĩa cách vẽ nét: màu, độ dày, đầu nét, góc nối, nét đứt.",
      docUrl: `${DOC}stroke/`,
      snapshotId: "visualize-stroke",
      params: [
        { name: "paint", type: "auto | color | gradient | tiling", default: "black", desc: "Màu/chuyển sắc của nét." },
        { name: "thickness", type: "auto | length", default: "1pt", desc: "Độ dày nét." },
        { name: "cap", type: "auto | str", default: '"butt"', desc: 'Kiểu đầu nét: "butt", "round", "square".' },
        { name: "join", type: "auto | str", default: '"miter"', desc: 'Kiểu góc nối: "miter", "round", "bevel".' },
        { name: "dash", type: "none | auto | str | array | dictionary", default: "none", desc: 'Mẫu nét đứt: "dotted", "dashed", "dash-dotted"...' },
        { name: "miter-limit", type: "auto | float", default: "4.0", desc: "Giới hạn tỉ lệ nhô ra của góc nhọn so với độ dày nét." },
      ],
      examples: [`#line(length: 4cm, stroke: (paint: blue, thickness: 3pt,
                          cap: "round", dash: "dashed"))`],
      paramExamples: [
        { caption: "dash — các kiểu nét đứt", snapshotId: "visualize-stroke-dash", code: `#stack(dir: ttb, spacing: 8pt,
  line(length: 4cm, stroke: (thickness: 1.5pt, dash: "solid")),
  line(length: 4cm, stroke: (thickness: 1.5pt, dash: "dashed")),
  line(length: 4cm, stroke: (thickness: 1.5pt, dash: "dotted")),
)` },
        { caption: "thickness — độ dày tăng dần", snapshotId: "visualize-stroke-thickness", code: `#stack(dir: ttb, spacing: 8pt,
  line(length: 4cm, stroke: 0.5pt),
  line(length: 4cm, stroke: 1.5pt),
  line(length: 4cm, stroke: 3pt),
)` },
      ],
    },
    {
      name: "color",
      slug: "color",
      kind: "type",
      signature: "luma() · rgb() · oklab() · oklch() · cmyk() · hsl() · hsv() · linear-rgb() · spot()",
      summary: "Kiểu màu trong một không gian màu; gồm hàm khởi tạo và phương thức biến đổi (lighten/darken/mix/...).",
      docUrl: `${DOC}color/`,
      snapshotId: "visualize-color",
      params: [
        { name: "luma(lightness, alpha)", type: "→ color", desc: "Màu xám theo độ sáng." },
        { name: "rgb(r, g, b, a) | rgb(hex)", type: "→ color", desc: "Màu RGB (hoặc chuỗi hex)." },
        { name: "oklab(l, a, b, alpha)", type: "→ color", desc: "Không gian Oklab (đều về cảm nhận)." },
        { name: "oklch(l, chroma, hue, alpha)", type: "→ color", desc: "Oklch — sáng/độ thuần/sắc độ." },
        { name: "cmyk(c, m, y, k)", type: "→ color", desc: "Màu CMYK (in ấn)." },
        { name: "hsl/hsv(hue, s, l/v, a)", type: "→ color", desc: "Hue–Saturation–Lightness/Value." },
        { name: ".lighten/.darken(ratio)", type: "method → color", desc: "Làm sáng/tối theo tỉ lệ." },
        { name: ".mix(..colors, space)", type: "method → color", desc: "Trộn nhiều màu." },
      ],
      examples: [`#square(fill: rgb("#007bff"))
#square(fill: oklch(70%, 0.15, 30deg).lighten(20%))`],
      members: [
        {
          name: "luma", slug: "luma", kind: "function",
          signature: "luma(lightness, alpha)",
          summary: "Màu xám theo độ sáng.",
          docUrl: `${DOC}color/#definitions-luma`,
          params: [
            { name: "lightness", type: "int | ratio", positional: true, desc: "Độ sáng (0–255 hoặc 0%–100%)." },
            { name: "alpha", type: "int | ratio", default: "100%", positional: true, desc: "Độ mờ đục." },
          ],
        },
        {
          name: "rgb", slug: "rgb", kind: "function",
          signature: 'rgb(red, green, blue, alpha)  ·  rgb("#rrggbb")',
          summary: "Màu RGB từ ba kênh, hoặc từ chuỗi hex.",
          docUrl: `${DOC}color/#definitions-rgb`,
          params: [
            { name: "red / green / blue", type: "int | ratio", positional: true, desc: "Kênh màu (0–255 hoặc %)." },
            { name: "alpha", type: "int | ratio", default: "100%", positional: true, desc: "Độ mờ đục." },
            { name: "hex", type: "str", desc: 'Hoặc truyền một chuỗi hex, vd "#007bff".' },
          ],
        },
        {
          name: "oklch", slug: "oklch", kind: "function",
          signature: "oklch(lightness, chroma, hue, alpha)",
          summary: "Không gian Oklch — sáng / độ thuần / sắc độ (đều về cảm nhận).",
          docUrl: `${DOC}color/#definitions-oklch`,
          params: [
            { name: "lightness", type: "ratio", positional: true, desc: "Độ sáng." },
            { name: "chroma", type: "float | ratio", positional: true, desc: "Độ thuần màu." },
            { name: "hue", type: "angle", positional: true, desc: "Sắc độ (góc)." },
            { name: "alpha", type: "ratio", default: "100%", positional: true, desc: "Độ mờ đục." },
          ],
        },
        {
          name: "oklab", slug: "oklab", kind: "function",
          signature: "oklab(lightness, a, b, alpha)",
          summary: "Không gian Oklab (đều về cảm nhận).",
          docUrl: `${DOC}color/#definitions-oklab`,
          params: [
            { name: "lightness", type: "ratio", positional: true, desc: "Độ sáng." },
            { name: "a / b", type: "float | ratio", positional: true, desc: "Trục màu a/b." },
            { name: "alpha", type: "ratio", default: "100%", positional: true, desc: "Độ mờ đục." },
          ],
        },
        {
          name: "cmyk", slug: "cmyk", kind: "function",
          signature: "cmyk(cyan, magenta, yellow, key)",
          summary: "Màu CMYK (in ấn).",
          docUrl: `${DOC}color/#definitions-cmyk`,
          params: [{ name: "cyan / magenta / yellow / key", type: "ratio", positional: true, desc: "Bốn kênh mực in (0%–100%)." }],
        },
        {
          name: "hsl", slug: "hsl", kind: "function",
          signature: "hsl(hue, saturation, lightness, alpha)",
          summary: "Hue – Saturation – Lightness.",
          docUrl: `${DOC}color/#definitions-hsl`,
          params: [
            { name: "hue", type: "angle", positional: true, desc: "Sắc độ (góc)." },
            { name: "saturation", type: "int | ratio", positional: true, desc: "Độ bão hoà." },
            { name: "lightness", type: "int | ratio", positional: true, desc: "Độ sáng." },
            { name: "alpha", type: "int | ratio", default: "100%", positional: true, desc: "Độ mờ đục." },
          ],
        },
      ],
    },
    {
      name: "gradient",
      slug: "gradient",
      kind: "type",
      signature: "gradient.linear() · gradient.radial() · gradient.conic()",
      summary: "Chuyển sắc màu (tuyến tính/tỏa tròn/hình nón) dùng để tô fill hoặc stroke.",
      docUrl: `${DOC}gradient/`,
      snapshotId: "visualize-gradient",
      params: [
        { name: "gradient.linear(..stops, angle, space, relative, dir)", type: "→ gradient", desc: "Chuyển sắc dọc theo một đường thẳng (angle là hướng)." },
        { name: "gradient.radial(..stops, center, radius, focal-center, focal-radius, space)", type: "→ gradient", desc: "Chuyển sắc tỏa ra từ một tâm." },
        { name: "gradient.conic(..stops, angle, center, space)", type: "→ gradient", desc: "Chuyển sắc xoay quanh một tâm." },
        { name: "stops", type: "color | (color, ratio)", positional: true, desc: "Các mốc màu (biến thiên ..); kèm tỉ lệ vị trí tùy chọn." },
        { name: "space", type: "function", default: "oklab", desc: "Không gian nội suy màu (mặc định Oklab đều về cảm nhận)." },
        { name: "relative", type: "auto | str", default: "auto", desc: 'Mốc tham chiếu: "self" hoặc "parent".' },
      ],
      examples: [`#rect(width: 5cm, height: 1.4cm,
     fill: gradient.linear(blue, purple, red))`],
      paramExamples: [
        { caption: "linear — góc 45°", snapshotId: "visualize-gradient-linear", code: `#rect(width: 5cm, height: 1.2cm, fill: gradient.linear(blue, red, angle: 45deg))` },
        { caption: "radial — tỏa từ tâm", snapshotId: "visualize-gradient-radial", code: `#circle(radius: 28pt, fill: gradient.radial(yellow, red))` },
        { caption: "conic — xoay quanh tâm", snapshotId: "visualize-gradient-conic", code: `#circle(radius: 28pt, fill: gradient.conic(blue, purple, red))` },
      ],
      members: [
        {
          name: "gradient.linear", slug: "gradient.linear", kind: "function",
          signature: "gradient.linear(..stops, dir, angle, space, relative)",
          summary: "Chuyển sắc dọc theo một đường thẳng.",
          docUrl: `${DOC}gradient/#definitions-linear`,
          params: [
            { name: "stops", type: "color | (color, ratio)", positional: true, desc: "Các mốc màu (biến thiên ..)." },
            { name: "angle", type: "angle", default: "0deg", desc: "Hướng chuyển sắc." },
            { name: "space", type: "function", default: "oklab", desc: "Không gian nội suy màu." },
            { name: "relative", type: "auto | str", default: "auto", desc: '"self" hoặc "parent".' },
          ],
        },
        {
          name: "gradient.radial", slug: "gradient.radial", kind: "function",
          signature: "gradient.radial(..stops, center, radius, focal-center, focal-radius, space, relative)",
          summary: "Chuyển sắc tỏa ra từ một tâm.",
          docUrl: `${DOC}gradient/#definitions-radial`,
          params: [
            { name: "stops", type: "color | (color, ratio)", positional: true, desc: "Các mốc màu." },
            { name: "center", type: "array", default: "(50%, 50%)", desc: "Tâm hình tròn ngoài." },
            { name: "radius", type: "ratio", default: "50%", desc: "Bán kính." },
            { name: "focal-center", type: "auto | array", default: "auto", desc: "Tâm hình tròn trong." },
            { name: "focal-radius", type: "ratio", default: "0%", desc: "Bán kính trong." },
          ],
        },
        {
          name: "gradient.conic", slug: "gradient.conic", kind: "function",
          signature: "gradient.conic(..stops, angle, center, space, relative)",
          summary: "Chuyển sắc xoay quanh một tâm.",
          docUrl: `${DOC}gradient/#definitions-conic`,
          params: [
            { name: "stops", type: "color | (color, ratio)", positional: true, desc: "Các mốc màu." },
            { name: "angle", type: "angle", default: "0deg", desc: "Góc bắt đầu." },
            { name: "center", type: "array", default: "(50%, 50%)", desc: "Tâm xoay." },
          ],
        },
      ],
    },
    {
      name: "tiling",
      slug: "tiling",
      kind: "type",
      signature: "tiling(body, size, spacing, relative)",
      summary: "Họa tiết lặp lại dùng làm phần tô (fill).",
      docUrl: `${DOC}tiling/`,
      snapshotId: "visualize-tiling",
      versionNote: "Tên mới của `pattern` (đổi ở Typst v0.13).",
      params: [
        { name: "body", type: "content", positional: true, desc: "Nội dung của một ô họa tiết (bắt buộc)." },
        { name: "size", type: "auto | array", default: "auto", desc: "Kích thước ô họa tiết." },
        { name: "spacing", type: "array", default: "(0pt, 0pt)", desc: "Khoảng cách giữa các ô lặp." },
        { name: "relative", type: "auto | str", default: "auto", desc: 'Mốc tham chiếu: "self" hoặc "parent".' },
      ],
      examples: [`#let oton = tiling(size: (10pt, 10pt))[
  #place(line(start: (0%, 0%), end: (100%, 100%)))
]
#rect(width: 4cm, height: 1.4cm, fill: oton)`],
    },
  ],
};
